/* valadovamemberaccessmodule.c generated by valac, the Vala compiler
 * generated from valadovamemberaccessmodule.vala, do not modify */

/* valadovamemberaccessmodule.vala
 *
 * Copyright (C) 2006-2011  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include <glib.h>
#include <glib-object.h>
#include <vala.h>
#include <valaccode.h>
#include <stdlib.h>
#include <string.h>
#include <valagee.h>


#define VALA_TYPE_DOVA_BASE_MODULE (vala_dova_base_module_get_type ())
#define VALA_DOVA_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_BASE_MODULE, ValaDovaBaseModule))
#define VALA_DOVA_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_BASE_MODULE, ValaDovaBaseModuleClass))
#define VALA_IS_DOVA_BASE_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_BASE_MODULE))
#define VALA_IS_DOVA_BASE_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_BASE_MODULE))
#define VALA_DOVA_BASE_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_BASE_MODULE, ValaDovaBaseModuleClass))

typedef struct _ValaDovaBaseModule ValaDovaBaseModule;
typedef struct _ValaDovaBaseModuleClass ValaDovaBaseModuleClass;
typedef struct _ValaDovaBaseModulePrivate ValaDovaBaseModulePrivate;

#define VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT (vala_dova_base_module_emit_context_get_type ())
#define VALA_DOVA_BASE_MODULE_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaDovaBaseModuleEmitContext))
#define VALA_DOVA_BASE_MODULE_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaDovaBaseModuleEmitContextClass))
#define VALA_DOVA_BASE_MODULE_IS_EMIT_CONTEXT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_DOVA_BASE_MODULE_IS_EMIT_CONTEXT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT))
#define VALA_DOVA_BASE_MODULE_EMIT_CONTEXT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DOVA_BASE_MODULE_TYPE_EMIT_CONTEXT, ValaDovaBaseModuleEmitContextClass))

typedef struct _ValaDovaBaseModuleEmitContext ValaDovaBaseModuleEmitContext;
typedef struct _ValaDovaBaseModuleEmitContextClass ValaDovaBaseModuleEmitContextClass;

#define VALA_TYPE_DOVA_STRUCT_MODULE (vala_dova_struct_module_get_type ())
#define VALA_DOVA_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_STRUCT_MODULE, ValaDovaStructModule))
#define VALA_DOVA_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_STRUCT_MODULE, ValaDovaStructModuleClass))
#define VALA_IS_DOVA_STRUCT_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_STRUCT_MODULE))
#define VALA_IS_DOVA_STRUCT_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_STRUCT_MODULE))
#define VALA_DOVA_STRUCT_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_STRUCT_MODULE, ValaDovaStructModuleClass))

typedef struct _ValaDovaStructModule ValaDovaStructModule;
typedef struct _ValaDovaStructModuleClass ValaDovaStructModuleClass;
typedef struct _ValaDovaStructModulePrivate ValaDovaStructModulePrivate;

#define VALA_TYPE_DOVA_METHOD_MODULE (vala_dova_method_module_get_type ())
#define VALA_DOVA_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_METHOD_MODULE, ValaDovaMethodModule))
#define VALA_DOVA_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_METHOD_MODULE, ValaDovaMethodModuleClass))
#define VALA_IS_DOVA_METHOD_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_METHOD_MODULE))
#define VALA_IS_DOVA_METHOD_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_METHOD_MODULE))
#define VALA_DOVA_METHOD_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_METHOD_MODULE, ValaDovaMethodModuleClass))

typedef struct _ValaDovaMethodModule ValaDovaMethodModule;
typedef struct _ValaDovaMethodModuleClass ValaDovaMethodModuleClass;
typedef struct _ValaDovaMethodModulePrivate ValaDovaMethodModulePrivate;

#define VALA_TYPE_DOVA_CONTROL_FLOW_MODULE (vala_dova_control_flow_module_get_type ())
#define VALA_DOVA_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, ValaDovaControlFlowModule))
#define VALA_DOVA_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, ValaDovaControlFlowModuleClass))
#define VALA_IS_DOVA_CONTROL_FLOW_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE))
#define VALA_IS_DOVA_CONTROL_FLOW_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE))
#define VALA_DOVA_CONTROL_FLOW_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, ValaDovaControlFlowModuleClass))

typedef struct _ValaDovaControlFlowModule ValaDovaControlFlowModule;
typedef struct _ValaDovaControlFlowModuleClass ValaDovaControlFlowModuleClass;
typedef struct _ValaDovaControlFlowModulePrivate ValaDovaControlFlowModulePrivate;

#define VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE (vala_dova_member_access_module_get_type ())
#define VALA_DOVA_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE, ValaDovaMemberAccessModule))
#define VALA_DOVA_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE, ValaDovaMemberAccessModuleClass))
#define VALA_IS_DOVA_MEMBER_ACCESS_MODULE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE))
#define VALA_IS_DOVA_MEMBER_ACCESS_MODULE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE))
#define VALA_DOVA_MEMBER_ACCESS_MODULE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_MEMBER_ACCESS_MODULE, ValaDovaMemberAccessModuleClass))

typedef struct _ValaDovaMemberAccessModule ValaDovaMemberAccessModule;
typedef struct _ValaDovaMemberAccessModuleClass ValaDovaMemberAccessModuleClass;
typedef struct _ValaDovaMemberAccessModulePrivate ValaDovaMemberAccessModulePrivate;
#define _vala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_ccode_node_unref (var), NULL)))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_target_value_unref0(var) ((var == NULL) ? NULL : (var = (vala_target_value_unref (var), NULL)))

#define VALA_TYPE_DOVA_VALUE (vala_dova_value_get_type ())
#define VALA_DOVA_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_TYPE_DOVA_VALUE, ValaDovaValue))
#define VALA_DOVA_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_TYPE_DOVA_VALUE, ValaDovaValueClass))
#define VALA_IS_DOVA_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_TYPE_DOVA_VALUE))
#define VALA_IS_DOVA_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_TYPE_DOVA_VALUE))
#define VALA_DOVA_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_TYPE_DOVA_VALUE, ValaDovaValueClass))

typedef struct _ValaDovaValue ValaDovaValue;
typedef struct _ValaDovaValueClass ValaDovaValueClass;
typedef struct _ValaDovaValuePrivate ValaDovaValuePrivate;

struct _ValaDovaBaseModule {
	ValaCodeGenerator parent_instance;
	ValaDovaBaseModulePrivate * priv;
	ValaSymbol* root_symbol;
	ValaDovaBaseModuleEmitContext* emit_context;
	ValaCCodeFile* header_file;
	ValaCCodeFile* cfile;
	ValaList* static_fields;
	gint next_wrapper_id;
	ValaDataType* void_type;
	ValaDataType* bool_type;
	ValaDataType* char_type;
	ValaDataType* int_type;
	ValaDataType* uint_type;
	ValaDataType* string_type;
	ValaClass* object_class;
	ValaClass* type_class;
	ValaClass* value_class;
	ValaClass* string_class;
	ValaStruct* array_struct;
	ValaClass* delegate_class;
	ValaClass* error_class;
};

struct _ValaDovaBaseModuleClass {
	ValaCodeGeneratorClass parent_class;
	void (*generate_struct_declaration) (ValaDovaBaseModule* self, ValaStruct* st, ValaCCodeFile* decl_space);
	void (*generate_delegate_declaration) (ValaDovaBaseModule* self, ValaDelegate* d, ValaCCodeFile* decl_space);
	void (*generate_cparameters) (ValaDovaBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space, ValaCCodeFunction* func, ValaCCodeFunctionDeclarator* vdeclarator, ValaCCodeFunctionCall* vcall);
	void (*generate_property_accessor_declaration) (ValaDovaBaseModule* self, ValaPropertyAccessor* acc, ValaCCodeFile* decl_space);
	ValaCCodeExpression* (*get_dup_func_expression) (ValaDovaBaseModule* self, ValaDataType* type, ValaSourceReference* source_reference, gboolean is_chainup);
	void (*append_local_free) (ValaDovaBaseModule* self, ValaSymbol* sym, gboolean stop_at_loop, ValaCodeNode* stop_at);
	ValaCCodeExpression* (*get_ref_cexpression) (ValaDovaBaseModule* self, ValaDataType* expression_type, ValaCCodeExpression* cexpr, ValaExpression* expr, ValaCodeNode* node);
	void (*generate_class_declaration) (ValaDovaBaseModule* self, ValaClass* cl, ValaCCodeFile* decl_space);
	void (*generate_interface_declaration) (ValaDovaBaseModule* self, ValaInterface* iface, ValaCCodeFile* decl_space);
	void (*generate_method_declaration) (ValaDovaBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space);
	ValaCCodeExpression* (*get_implicit_cast_expression) (ValaDovaBaseModule* self, ValaCCodeExpression* source_cexpr, ValaDataType* expression_type, ValaDataType* target_type, ValaExpression* expr);
	gchar* (*get_custom_creturn_type) (ValaDovaBaseModule* self, ValaMethod* m);
	gboolean (*method_has_wrapper) (ValaDovaBaseModule* self, ValaMethod* method);
	void (*add_simple_check) (ValaDovaBaseModule* self, ValaCodeNode* node, gboolean always_fails);
};

struct _ValaDovaStructModule {
	ValaDovaBaseModule parent_instance;
	ValaDovaStructModulePrivate * priv;
};

struct _ValaDovaStructModuleClass {
	ValaDovaBaseModuleClass parent_class;
};

struct _ValaDovaMethodModule {
	ValaDovaStructModule parent_instance;
	ValaDovaMethodModulePrivate * priv;
};

struct _ValaDovaMethodModuleClass {
	ValaDovaStructModuleClass parent_class;
};

struct _ValaDovaControlFlowModule {
	ValaDovaMethodModule parent_instance;
	ValaDovaControlFlowModulePrivate * priv;
};

struct _ValaDovaControlFlowModuleClass {
	ValaDovaMethodModuleClass parent_class;
};

struct _ValaDovaMemberAccessModule {
	ValaDovaControlFlowModule parent_instance;
	ValaDovaMemberAccessModulePrivate * priv;
};

struct _ValaDovaMemberAccessModuleClass {
	ValaDovaControlFlowModuleClass parent_class;
};

struct _ValaDovaValue {
	ValaTargetValue parent_instance;
	ValaDovaValuePrivate * priv;
	ValaCCodeExpression* cvalue;
};

struct _ValaDovaValueClass {
	ValaTargetValueClass parent_class;
};


static gpointer vala_dova_member_access_module_parent_class = NULL;

GType vala_dova_base_module_get_type (void) G_GNUC_CONST;
gpointer vala_dova_base_module_emit_context_ref (gpointer instance);
void vala_dova_base_module_emit_context_unref (gpointer instance);
GParamSpec* vala_dova_base_module_param_spec_emit_context (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void vala_dova_base_module_value_set_emit_context (GValue* value, gpointer v_object);
void vala_dova_base_module_value_take_emit_context (GValue* value, gpointer v_object);
gpointer vala_dova_base_module_value_get_emit_context (const GValue* value);
GType vala_dova_base_module_emit_context_get_type (void) G_GNUC_CONST;
GType vala_dova_struct_module_get_type (void) G_GNUC_CONST;
GType vala_dova_method_module_get_type (void) G_GNUC_CONST;
GType vala_dova_control_flow_module_get_type (void) G_GNUC_CONST;
GType vala_dova_member_access_module_get_type (void) G_GNUC_CONST;
enum  {
	VALA_DOVA_MEMBER_ACCESS_MODULE_DUMMY_PROPERTY
};
static void vala_dova_member_access_module_real_visit_member_access (ValaCodeVisitor* base, ValaMemberAccess* expr);
ValaCCodeExpression* vala_dova_base_module_get_cvalue (ValaDovaBaseModule* self, ValaExpression* expr);
void vala_dova_base_module_generate_method_declaration (ValaDovaBaseModule* self, ValaMethod* m, ValaCCodeFile* decl_space);
gboolean vala_dova_base_module_add_generated_external_symbol (ValaDovaBaseModule* self, ValaSymbol* external_symbol);
void vala_dova_base_module_set_cvalue (ValaDovaBaseModule* self, ValaExpression* expr, ValaCCodeExpression* cvalue);
gchar* vala_dova_base_module_get_ccode_lower_case_name (ValaDovaBaseModule* self, ValaCodeNode* node, const gchar* infix);
gboolean vala_dova_base_module_method_has_wrapper (ValaDovaBaseModule* self, ValaMethod* method);
ValaLocalVariable* vala_dova_base_module_get_temp_variable (ValaDovaBaseModule* self, ValaDataType* type, gboolean value_owned, ValaCodeNode* node_reference);
void vala_dova_base_module_emit_temp_var (ValaDovaBaseModule* self, ValaLocalVariable* local);
gchar* vala_dova_base_module_get_ccode_upper_case_name (ValaDovaBaseModule* self, ValaSymbol* node, const gchar* infix);
gchar* vala_dova_base_module_get_ccode_name (ValaDovaBaseModule* self, ValaCodeNode* node);
gchar* vala_dova_base_module_get_ccode_real_name (ValaDovaBaseModule* self, ValaMethod* node);
void vala_dova_base_module_generate_enum_declaration (ValaDovaBaseModule* self, ValaEnum* en, ValaCCodeFile* decl_space);
void vala_dova_base_module_generate_constant_declaration (ValaDovaBaseModule* self, ValaConstant* c, ValaCCodeFile* decl_space);
void vala_dova_base_module_generate_property_accessor_declaration (ValaDovaBaseModule* self, ValaPropertyAccessor* acc, ValaCCodeFile* decl_space);
ValaClass* vala_dova_base_module_get_current_class (ValaDovaBaseModule* self);
ValaTargetValue* vala_dova_member_access_module_get_local_cvalue (ValaDovaMemberAccessModule* self, ValaLocalVariable* local);
ValaDovaValue* vala_dova_value_new (ValaDataType* value_type, ValaCCodeExpression* cvalue);
ValaDovaValue* vala_dova_value_construct (GType object_type, ValaDataType* value_type, ValaCCodeExpression* cvalue);
GType vala_dova_value_get_type (void) G_GNUC_CONST;
ValaCCodeExpression* vala_dova_base_module_get_variable_cexpression (ValaDovaBaseModule* self, const gchar* name);
gint vala_dova_base_module_get_block_id (ValaDovaBaseModule* self, ValaBlock* b);
gchar* vala_dova_base_module_get_variable_cname (ValaDovaBaseModule* self, const gchar* name);
ValaTargetValue* vala_dova_member_access_module_get_parameter_cvalue (ValaDovaMemberAccessModule* self, ValaParameter* p);
ValaMethod* vala_dova_base_module_get_current_method (ValaDovaBaseModule* self);
ValaTypeSymbol* vala_dova_base_module_get_current_type_symbol (ValaDovaBaseModule* self);
ValaPropertyAccessor* vala_dova_base_module_get_current_property_accessor (ValaDovaBaseModule* self);
ValaTargetValue* vala_dova_member_access_module_get_field_cvalue (ValaDovaMemberAccessModule* self, ValaField* f, ValaTargetValue* instance);
ValaCCodeExpression* vala_dova_base_module_get_cvalue_ (ValaDovaBaseModule* self, ValaTargetValue* value);
ValaDataType* vala_dova_base_module_get_data_type_for_symbol (ValaTypeSymbol* sym);
void vala_dova_base_module_generate_field_declaration (ValaDovaBaseModule* self, ValaField* f, ValaCCodeFile* decl_space);
static ValaTargetValue* vala_dova_member_access_module_load_variable (ValaDovaMemberAccessModule* self, ValaVariable* variable, ValaTargetValue* value);
static ValaTargetValue* vala_dova_member_access_module_real_load_local (ValaCodeGenerator* base, ValaLocalVariable* local);
static ValaTargetValue* vala_dova_member_access_module_real_load_parameter (ValaCodeGenerator* base, ValaParameter* param);
static ValaTargetValue* vala_dova_member_access_module_real_load_field (ValaCodeGenerator* base, ValaField* field, ValaTargetValue* instance);
ValaDovaMemberAccessModule* vala_dova_member_access_module_construct (GType object_type);
ValaDovaControlFlowModule* vala_dova_control_flow_module_construct (GType object_type);


static gpointer _vala_code_node_ref0 (gpointer self) {
	return self ? vala_code_node_ref (self) : NULL;
}


static gpointer _vala_ccode_node_ref0 (gpointer self) {
	return self ? vala_ccode_node_ref (self) : NULL;
}


static void vala_dova_member_access_module_real_visit_member_access (ValaCodeVisitor* base, ValaMemberAccess* expr) {
	ValaDovaMemberAccessModule * self;
	ValaCCodeExpression* pub_inst;
	ValaDataType* base_type;
	ValaMemberAccess* _tmp0_;
	ValaExpression* _tmp1_;
	ValaExpression* _tmp2_;
	ValaMemberAccess* _tmp18_;
	ValaSymbol* _tmp19_;
	ValaSymbol* _tmp20_;
	self = (ValaDovaMemberAccessModule*) base;
	g_return_if_fail (expr != NULL);
	pub_inst = NULL;
	base_type = NULL;
	_tmp0_ = expr;
	_tmp1_ = vala_member_access_get_inner (_tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		ValaMemberAccess* _tmp3_;
		ValaExpression* _tmp4_;
		ValaExpression* _tmp5_;
		ValaCCodeExpression* _tmp6_ = NULL;
		ValaMemberAccess* _tmp7_;
		ValaExpression* _tmp8_;
		ValaExpression* _tmp9_;
		ValaDataType* _tmp10_;
		ValaDataType* _tmp11_;
		_tmp3_ = expr;
		_tmp4_ = vala_member_access_get_inner (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp6_ = vala_dova_base_module_get_cvalue ((ValaDovaBaseModule*) self, _tmp5_);
		_vala_ccode_node_unref0 (pub_inst);
		pub_inst = _tmp6_;
		_tmp7_ = expr;
		_tmp8_ = vala_member_access_get_inner (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = vala_expression_get_value_type (_tmp9_);
		_tmp11_ = _tmp10_;
		if (_tmp11_ != NULL) {
			ValaMemberAccess* _tmp12_;
			ValaExpression* _tmp13_;
			ValaExpression* _tmp14_;
			ValaDataType* _tmp15_;
			ValaDataType* _tmp16_;
			ValaDataType* _tmp17_;
			_tmp12_ = expr;
			_tmp13_ = vala_member_access_get_inner (_tmp12_);
			_tmp14_ = _tmp13_;
			_tmp15_ = vala_expression_get_value_type (_tmp14_);
			_tmp16_ = _tmp15_;
			_tmp17_ = _vala_code_node_ref0 (_tmp16_);
			_vala_code_node_unref0 (base_type);
			base_type = _tmp17_;
		}
	}
	_tmp18_ = expr;
	_tmp19_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp18_);
	_tmp20_ = _tmp19_;
	if (VALA_IS_METHOD (_tmp20_)) {
		ValaMemberAccess* _tmp21_;
		ValaSymbol* _tmp22_;
		ValaSymbol* _tmp23_;
		ValaMethod* _tmp24_;
		ValaMethod* m;
		ValaMethod* _tmp25_;
		ValaMemberAccess* _tmp39_;
		ValaExpression* _tmp40_;
		ValaExpression* _tmp41_;
		ValaMethod* _tmp82_;
		ValaMethod* _tmp83_;
		ValaMethod* _tmp84_;
		_tmp21_ = expr;
		_tmp22_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp21_);
		_tmp23_ = _tmp22_;
		_tmp24_ = _vala_code_node_ref0 (VALA_METHOD (_tmp23_));
		m = _tmp24_;
		_tmp25_ = m;
		if (!VALA_IS_DYNAMIC_METHOD (_tmp25_)) {
			ValaMethod* _tmp26_;
			ValaCCodeFile* _tmp27_;
			gboolean _tmp28_ = FALSE;
			ValaMethod* _tmp29_;
			gboolean _tmp30_;
			gboolean _tmp31_;
			gboolean _tmp35_;
			_tmp26_ = m;
			_tmp27_ = ((ValaDovaBaseModule*) self)->cfile;
			vala_dova_base_module_generate_method_declaration ((ValaDovaBaseModule*) self, _tmp26_, _tmp27_);
			_tmp29_ = m;
			_tmp30_ = vala_symbol_get_external ((ValaSymbol*) _tmp29_);
			_tmp31_ = _tmp30_;
			if (!_tmp31_) {
				ValaMethod* _tmp32_;
				gboolean _tmp33_;
				gboolean _tmp34_;
				_tmp32_ = m;
				_tmp33_ = vala_symbol_get_external_package ((ValaSymbol*) _tmp32_);
				_tmp34_ = _tmp33_;
				_tmp28_ = _tmp34_;
			} else {
				_tmp28_ = FALSE;
			}
			_tmp35_ = _tmp28_;
			if (_tmp35_) {
				ValaMethod* _tmp36_;
				gboolean _tmp37_ = FALSE;
				_tmp36_ = m;
				_tmp37_ = vala_dova_base_module_add_generated_external_symbol ((ValaDovaBaseModule*) self, (ValaSymbol*) _tmp36_);
				if (_tmp37_) {
					ValaMethod* _tmp38_;
					_tmp38_ = m;
					vala_code_visitor_visit_method ((ValaCodeVisitor*) self, _tmp38_);
				}
			}
		}
		_tmp39_ = expr;
		_tmp40_ = vala_member_access_get_inner (_tmp39_);
		_tmp41_ = _tmp40_;
		if (VALA_IS_BASE_ACCESS (_tmp41_)) {
			ValaMethod* _tmp42_;
			ValaMethod* _tmp43_;
			ValaMethod* _tmp44_;
			_tmp42_ = m;
			_tmp43_ = vala_method_get_base_method (_tmp42_);
			_tmp44_ = _tmp43_;
			if (_tmp44_ != NULL) {
				ValaMethod* _tmp45_;
				ValaMethod* _tmp46_;
				ValaMethod* _tmp47_;
				ValaSymbol* _tmp48_;
				ValaSymbol* _tmp49_;
				ValaClass* _tmp50_;
				ValaClass* base_class;
				ValaMemberAccess* _tmp51_;
				ValaClass* _tmp52_;
				gchar* _tmp53_ = NULL;
				gchar* _tmp54_;
				ValaMethod* _tmp55_;
				const gchar* _tmp56_;
				const gchar* _tmp57_;
				gchar* _tmp58_ = NULL;
				gchar* _tmp59_;
				ValaCCodeIdentifier* _tmp60_;
				ValaCCodeIdentifier* _tmp61_;
				_tmp45_ = m;
				_tmp46_ = vala_method_get_base_method (_tmp45_);
				_tmp47_ = _tmp46_;
				_tmp48_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp47_);
				_tmp49_ = _tmp48_;
				_tmp50_ = _vala_code_node_ref0 (VALA_CLASS (_tmp49_));
				base_class = _tmp50_;
				_tmp51_ = expr;
				_tmp52_ = base_class;
				_tmp53_ = vala_dova_base_module_get_ccode_lower_case_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp52_, NULL);
				_tmp54_ = _tmp53_;
				_tmp55_ = m;
				_tmp56_ = vala_symbol_get_name ((ValaSymbol*) _tmp55_);
				_tmp57_ = _tmp56_;
				_tmp58_ = g_strdup_printf ("%s_base_%s", _tmp54_, _tmp57_);
				_tmp59_ = _tmp58_;
				_tmp60_ = vala_ccode_identifier_new (_tmp59_);
				_tmp61_ = _tmp60_;
				vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp51_, (ValaCCodeExpression*) _tmp61_);
				_vala_ccode_node_unref0 (_tmp61_);
				_g_free0 (_tmp59_);
				_g_free0 (_tmp54_);
				_vala_code_node_unref0 (base_class);
				_vala_code_node_unref0 (m);
				_vala_code_node_unref0 (base_type);
				_vala_ccode_node_unref0 (pub_inst);
				return;
			} else {
				ValaMethod* _tmp62_;
				ValaMethod* _tmp63_;
				ValaMethod* _tmp64_;
				_tmp62_ = m;
				_tmp63_ = vala_method_get_base_interface_method (_tmp62_);
				_tmp64_ = _tmp63_;
				if (_tmp64_ != NULL) {
					ValaMethod* _tmp65_;
					ValaMethod* _tmp66_;
					ValaMethod* _tmp67_;
					ValaSymbol* _tmp68_;
					ValaSymbol* _tmp69_;
					ValaInterface* _tmp70_;
					ValaInterface* base_iface;
					ValaMemberAccess* _tmp71_;
					ValaInterface* _tmp72_;
					gchar* _tmp73_ = NULL;
					gchar* _tmp74_;
					ValaMethod* _tmp75_;
					const gchar* _tmp76_;
					const gchar* _tmp77_;
					gchar* _tmp78_ = NULL;
					gchar* _tmp79_;
					ValaCCodeIdentifier* _tmp80_;
					ValaCCodeIdentifier* _tmp81_;
					_tmp65_ = m;
					_tmp66_ = vala_method_get_base_interface_method (_tmp65_);
					_tmp67_ = _tmp66_;
					_tmp68_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp67_);
					_tmp69_ = _tmp68_;
					_tmp70_ = _vala_code_node_ref0 (VALA_INTERFACE (_tmp69_));
					base_iface = _tmp70_;
					_tmp71_ = expr;
					_tmp72_ = base_iface;
					_tmp73_ = vala_dova_base_module_get_ccode_lower_case_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp72_, NULL);
					_tmp74_ = _tmp73_;
					_tmp75_ = m;
					_tmp76_ = vala_symbol_get_name ((ValaSymbol*) _tmp75_);
					_tmp77_ = _tmp76_;
					_tmp78_ = g_strdup_printf ("%s_base_%s", _tmp74_, _tmp77_);
					_tmp79_ = _tmp78_;
					_tmp80_ = vala_ccode_identifier_new (_tmp79_);
					_tmp81_ = _tmp80_;
					vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp71_, (ValaCCodeExpression*) _tmp81_);
					_vala_ccode_node_unref0 (_tmp81_);
					_g_free0 (_tmp79_);
					_g_free0 (_tmp74_);
					_vala_code_node_unref0 (base_iface);
					_vala_code_node_unref0 (m);
					_vala_code_node_unref0 (base_type);
					_vala_ccode_node_unref0 (pub_inst);
					return;
				}
			}
		}
		_tmp82_ = m;
		_tmp83_ = vala_method_get_base_method (_tmp82_);
		_tmp84_ = _tmp83_;
		if (_tmp84_ != NULL) {
			ValaMethod* _tmp85_;
			ValaMethod* _tmp86_;
			ValaMethod* _tmp87_;
			gboolean _tmp88_ = FALSE;
			_tmp85_ = m;
			_tmp86_ = vala_method_get_base_method (_tmp85_);
			_tmp87_ = _tmp86_;
			_tmp88_ = vala_dova_base_module_method_has_wrapper ((ValaDovaBaseModule*) self, _tmp87_);
			if (!_tmp88_) {
				ValaCCodeExpression* _tmp89_;
				ValaCCodeExpression* _tmp90_;
				ValaCCodeExpression* inst;
				gboolean _tmp91_ = FALSE;
				ValaMemberAccess* _tmp92_;
				ValaExpression* _tmp93_;
				ValaExpression* _tmp94_;
				gboolean _tmp99_;
				ValaMethod* _tmp118_;
				ValaMethod* _tmp119_;
				ValaMethod* _tmp120_;
				ValaSymbol* _tmp121_;
				ValaSymbol* _tmp122_;
				ValaClass* _tmp123_;
				ValaClass* base_class;
				ValaClass* _tmp124_;
				gchar* _tmp125_ = NULL;
				gchar* _tmp126_;
				gchar* _tmp127_ = NULL;
				gchar* _tmp128_;
				ValaCCodeIdentifier* _tmp129_;
				ValaCCodeIdentifier* _tmp130_;
				ValaCCodeFunctionCall* _tmp131_;
				ValaCCodeFunctionCall* _tmp132_;
				ValaCCodeFunctionCall* vclass;
				ValaCCodeFunctionCall* _tmp133_;
				ValaCCodeExpression* _tmp134_;
				ValaMemberAccess* _tmp135_;
				ValaCCodeFunctionCall* _tmp136_;
				ValaMethod* _tmp137_;
				const gchar* _tmp138_;
				const gchar* _tmp139_;
				ValaCCodeMemberAccess* _tmp140_;
				ValaCCodeMemberAccess* _tmp141_;
				_tmp89_ = pub_inst;
				_tmp90_ = _vala_ccode_node_ref0 (_tmp89_);
				inst = _tmp90_;
				_tmp92_ = expr;
				_tmp93_ = vala_member_access_get_inner (_tmp92_);
				_tmp94_ = _tmp93_;
				if (_tmp94_ != NULL) {
					ValaMemberAccess* _tmp95_;
					ValaExpression* _tmp96_;
					ValaExpression* _tmp97_;
					gboolean _tmp98_ = FALSE;
					_tmp95_ = expr;
					_tmp96_ = vala_member_access_get_inner (_tmp95_);
					_tmp97_ = _tmp96_;
					_tmp98_ = vala_expression_is_pure (_tmp97_);
					_tmp91_ = !_tmp98_;
				} else {
					_tmp91_ = FALSE;
				}
				_tmp99_ = _tmp91_;
				if (_tmp99_) {
					ValaMemberAccess* _tmp100_;
					ValaExpression* _tmp101_;
					ValaExpression* _tmp102_;
					ValaDataType* _tmp103_;
					ValaDataType* _tmp104_;
					ValaLocalVariable* _tmp105_ = NULL;
					ValaLocalVariable* temp_var;
					ValaLocalVariable* _tmp106_;
					ValaLocalVariable* _tmp107_;
					const gchar* _tmp108_;
					const gchar* _tmp109_;
					ValaCCodeIdentifier* _tmp110_;
					ValaCCodeIdentifier* ctemp;
					ValaCCodeIdentifier* _tmp111_;
					ValaCCodeExpression* _tmp112_;
					ValaCCodeAssignment* _tmp113_;
					ValaMemberAccess* _tmp114_;
					ValaExpression* _tmp115_;
					ValaExpression* _tmp116_;
					ValaCCodeIdentifier* _tmp117_;
					_tmp100_ = expr;
					_tmp101_ = vala_member_access_get_inner (_tmp100_);
					_tmp102_ = _tmp101_;
					_tmp103_ = vala_expression_get_value_type (_tmp102_);
					_tmp104_ = _tmp103_;
					_tmp105_ = vala_dova_base_module_get_temp_variable ((ValaDovaBaseModule*) self, _tmp104_, TRUE, NULL);
					temp_var = _tmp105_;
					_tmp106_ = temp_var;
					vala_dova_base_module_emit_temp_var ((ValaDovaBaseModule*) self, _tmp106_);
					_tmp107_ = temp_var;
					_tmp108_ = vala_symbol_get_name ((ValaSymbol*) _tmp107_);
					_tmp109_ = _tmp108_;
					_tmp110_ = vala_ccode_identifier_new (_tmp109_);
					ctemp = _tmp110_;
					_tmp111_ = ctemp;
					_tmp112_ = pub_inst;
					_tmp113_ = vala_ccode_assignment_new ((ValaCCodeExpression*) _tmp111_, _tmp112_, VALA_CCODE_ASSIGNMENT_OPERATOR_SIMPLE);
					_vala_ccode_node_unref0 (inst);
					inst = (ValaCCodeExpression*) _tmp113_;
					_tmp114_ = expr;
					_tmp115_ = vala_member_access_get_inner (_tmp114_);
					_tmp116_ = _tmp115_;
					_tmp117_ = ctemp;
					vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, _tmp116_, (ValaCCodeExpression*) _tmp117_);
					_vala_ccode_node_unref0 (ctemp);
					_vala_code_node_unref0 (temp_var);
				}
				_tmp118_ = m;
				_tmp119_ = vala_method_get_base_method (_tmp118_);
				_tmp120_ = _tmp119_;
				_tmp121_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp120_);
				_tmp122_ = _tmp121_;
				_tmp123_ = _vala_code_node_ref0 (VALA_CLASS (_tmp122_));
				base_class = _tmp123_;
				_tmp124_ = base_class;
				_tmp125_ = vala_dova_base_module_get_ccode_upper_case_name ((ValaDovaBaseModule*) self, (ValaSymbol*) _tmp124_, NULL);
				_tmp126_ = _tmp125_;
				_tmp127_ = g_strdup_printf ("%s_GET_CLASS", _tmp126_);
				_tmp128_ = _tmp127_;
				_tmp129_ = vala_ccode_identifier_new (_tmp128_);
				_tmp130_ = _tmp129_;
				_tmp131_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp130_);
				_tmp132_ = _tmp131_;
				_vala_ccode_node_unref0 (_tmp130_);
				_g_free0 (_tmp128_);
				_g_free0 (_tmp126_);
				vclass = _tmp132_;
				_tmp133_ = vclass;
				_tmp134_ = inst;
				vala_ccode_function_call_add_argument (_tmp133_, _tmp134_);
				_tmp135_ = expr;
				_tmp136_ = vclass;
				_tmp137_ = m;
				_tmp138_ = vala_symbol_get_name ((ValaSymbol*) _tmp137_);
				_tmp139_ = _tmp138_;
				_tmp140_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) _tmp136_, _tmp139_);
				_tmp141_ = _tmp140_;
				vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp135_, (ValaCCodeExpression*) _tmp141_);
				_vala_ccode_node_unref0 (_tmp141_);
				_vala_ccode_node_unref0 (vclass);
				_vala_code_node_unref0 (base_class);
				_vala_ccode_node_unref0 (inst);
			} else {
				ValaMemberAccess* _tmp142_;
				ValaMethod* _tmp143_;
				ValaMethod* _tmp144_;
				ValaMethod* _tmp145_;
				gchar* _tmp146_ = NULL;
				gchar* _tmp147_;
				ValaCCodeIdentifier* _tmp148_;
				ValaCCodeIdentifier* _tmp149_;
				_tmp142_ = expr;
				_tmp143_ = m;
				_tmp144_ = vala_method_get_base_method (_tmp143_);
				_tmp145_ = _tmp144_;
				_tmp146_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp145_);
				_tmp147_ = _tmp146_;
				_tmp148_ = vala_ccode_identifier_new (_tmp147_);
				_tmp149_ = _tmp148_;
				vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp142_, (ValaCCodeExpression*) _tmp149_);
				_vala_ccode_node_unref0 (_tmp149_);
				_g_free0 (_tmp147_);
			}
		} else {
			ValaMethod* _tmp150_;
			ValaMethod* _tmp151_;
			ValaMethod* _tmp152_;
			_tmp150_ = m;
			_tmp151_ = vala_method_get_base_interface_method (_tmp150_);
			_tmp152_ = _tmp151_;
			if (_tmp152_ != NULL) {
				ValaMemberAccess* _tmp153_;
				ValaMethod* _tmp154_;
				ValaMethod* _tmp155_;
				ValaMethod* _tmp156_;
				gchar* _tmp157_ = NULL;
				gchar* _tmp158_;
				ValaCCodeIdentifier* _tmp159_;
				ValaCCodeIdentifier* _tmp160_;
				_tmp153_ = expr;
				_tmp154_ = m;
				_tmp155_ = vala_method_get_base_interface_method (_tmp154_);
				_tmp156_ = _tmp155_;
				_tmp157_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp156_);
				_tmp158_ = _tmp157_;
				_tmp159_ = vala_ccode_identifier_new (_tmp158_);
				_tmp160_ = _tmp159_;
				vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp153_, (ValaCCodeExpression*) _tmp160_);
				_vala_ccode_node_unref0 (_tmp160_);
				_g_free0 (_tmp158_);
			} else {
				ValaMethod* _tmp161_;
				_tmp161_ = m;
				if (VALA_IS_CREATION_METHOD (_tmp161_)) {
					ValaMemberAccess* _tmp162_;
					ValaMethod* _tmp163_;
					gchar* _tmp164_ = NULL;
					gchar* _tmp165_;
					ValaCCodeIdentifier* _tmp166_;
					ValaCCodeIdentifier* _tmp167_;
					_tmp162_ = expr;
					_tmp163_ = m;
					_tmp164_ = vala_dova_base_module_get_ccode_real_name ((ValaDovaBaseModule*) self, _tmp163_);
					_tmp165_ = _tmp164_;
					_tmp166_ = vala_ccode_identifier_new (_tmp165_);
					_tmp167_ = _tmp166_;
					vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp162_, (ValaCCodeExpression*) _tmp167_);
					_vala_ccode_node_unref0 (_tmp167_);
					_g_free0 (_tmp165_);
				} else {
					ValaMemberAccess* _tmp168_;
					ValaMethod* _tmp169_;
					gchar* _tmp170_ = NULL;
					gchar* _tmp171_;
					ValaCCodeIdentifier* _tmp172_;
					ValaCCodeIdentifier* _tmp173_;
					_tmp168_ = expr;
					_tmp169_ = m;
					_tmp170_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp169_);
					_tmp171_ = _tmp170_;
					_tmp172_ = vala_ccode_identifier_new (_tmp171_);
					_tmp173_ = _tmp172_;
					vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp168_, (ValaCCodeExpression*) _tmp173_);
					_vala_ccode_node_unref0 (_tmp173_);
					_g_free0 (_tmp171_);
				}
			}
		}
		_vala_code_node_unref0 (m);
	} else {
		ValaMemberAccess* _tmp174_;
		ValaSymbol* _tmp175_;
		ValaSymbol* _tmp176_;
		_tmp174_ = expr;
		_tmp175_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp174_);
		_tmp176_ = _tmp175_;
		if (VALA_IS_ARRAY_LENGTH_FIELD (_tmp176_)) {
			ValaMemberAccess* _tmp177_;
			ValaExpression* _tmp178_;
			ValaExpression* _tmp179_;
			ValaDataType* _tmp180_;
			ValaDataType* _tmp181_;
			ValaArrayType* _tmp182_;
			ValaArrayType* array_type;
			ValaArrayType* _tmp183_;
			gboolean _tmp184_;
			gboolean _tmp185_;
			_tmp177_ = expr;
			_tmp178_ = vala_member_access_get_inner (_tmp177_);
			_tmp179_ = _tmp178_;
			_tmp180_ = vala_expression_get_value_type (_tmp179_);
			_tmp181_ = _tmp180_;
			_tmp182_ = _vala_code_node_ref0 (VALA_ARRAY_TYPE (_tmp181_));
			array_type = _tmp182_;
			_tmp183_ = array_type;
			_tmp184_ = vala_array_type_get_fixed_length (_tmp183_);
			_tmp185_ = _tmp184_;
			if (_tmp185_) {
				ValaCCodeIdentifier* _tmp186_;
				ValaCCodeIdentifier* _tmp187_;
				ValaCCodeFunctionCall* _tmp188_;
				ValaCCodeFunctionCall* _tmp189_;
				ValaCCodeFunctionCall* csizeof;
				ValaCCodeFunctionCall* _tmp190_;
				ValaCCodeExpression* _tmp191_;
				ValaCCodeIdentifier* _tmp192_;
				ValaCCodeIdentifier* _tmp193_;
				ValaCCodeFunctionCall* _tmp194_;
				ValaCCodeFunctionCall* _tmp195_;
				ValaCCodeFunctionCall* csizeofelement;
				ValaCCodeFunctionCall* _tmp196_;
				ValaCCodeExpression* _tmp197_;
				ValaCCodeConstant* _tmp198_;
				ValaCCodeConstant* _tmp199_;
				ValaCCodeElementAccess* _tmp200_;
				ValaCCodeElementAccess* _tmp201_;
				ValaMemberAccess* _tmp202_;
				ValaCCodeFunctionCall* _tmp203_;
				ValaCCodeFunctionCall* _tmp204_;
				ValaCCodeBinaryExpression* _tmp205_;
				ValaCCodeBinaryExpression* _tmp206_;
				_tmp186_ = vala_ccode_identifier_new ("sizeof");
				_tmp187_ = _tmp186_;
				_tmp188_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp187_);
				_tmp189_ = _tmp188_;
				_vala_ccode_node_unref0 (_tmp187_);
				csizeof = _tmp189_;
				_tmp190_ = csizeof;
				_tmp191_ = pub_inst;
				vala_ccode_function_call_add_argument (_tmp190_, _tmp191_);
				_tmp192_ = vala_ccode_identifier_new ("sizeof");
				_tmp193_ = _tmp192_;
				_tmp194_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp193_);
				_tmp195_ = _tmp194_;
				_vala_ccode_node_unref0 (_tmp193_);
				csizeofelement = _tmp195_;
				_tmp196_ = csizeofelement;
				_tmp197_ = pub_inst;
				_tmp198_ = vala_ccode_constant_new ("0");
				_tmp199_ = _tmp198_;
				_tmp200_ = vala_ccode_element_access_new (_tmp197_, (ValaCCodeExpression*) _tmp199_);
				_tmp201_ = _tmp200_;
				vala_ccode_function_call_add_argument (_tmp196_, (ValaCCodeExpression*) _tmp201_);
				_vala_ccode_node_unref0 (_tmp201_);
				_vala_ccode_node_unref0 (_tmp199_);
				_tmp202_ = expr;
				_tmp203_ = csizeof;
				_tmp204_ = csizeofelement;
				_tmp205_ = vala_ccode_binary_expression_new (VALA_CCODE_BINARY_OPERATOR_DIV, (ValaCCodeExpression*) _tmp203_, (ValaCCodeExpression*) _tmp204_);
				_tmp206_ = _tmp205_;
				vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp202_, (ValaCCodeExpression*) _tmp206_);
				_vala_ccode_node_unref0 (_tmp206_);
				_vala_ccode_node_unref0 (csizeofelement);
				_vala_ccode_node_unref0 (csizeof);
			} else {
				ValaMemberAccess* _tmp207_;
				ValaCCodeExpression* _tmp208_;
				ValaCCodeMemberAccess* _tmp209_;
				ValaCCodeMemberAccess* _tmp210_;
				_tmp207_ = expr;
				_tmp208_ = pub_inst;
				_tmp209_ = vala_ccode_member_access_new (_tmp208_, "length", FALSE);
				_tmp210_ = _tmp209_;
				vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp207_, (ValaCCodeExpression*) _tmp210_);
				_vala_ccode_node_unref0 (_tmp210_);
			}
			_vala_code_node_unref0 (array_type);
		} else {
			ValaMemberAccess* _tmp211_;
			ValaSymbol* _tmp212_;
			ValaSymbol* _tmp213_;
			_tmp211_ = expr;
			_tmp212_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp211_);
			_tmp213_ = _tmp212_;
			if (VALA_IS_FIELD (_tmp213_)) {
				ValaMemberAccess* _tmp214_;
				ValaSymbol* _tmp215_;
				ValaSymbol* _tmp216_;
				ValaField* _tmp217_;
				ValaField* f;
				ValaTargetValue* _tmp218_ = NULL;
				ValaMemberAccess* _tmp219_;
				ValaExpression* _tmp220_;
				ValaExpression* _tmp221_;
				ValaMemberAccess* _tmp227_;
				ValaField* _tmp228_;
				ValaTargetValue* _tmp229_;
				ValaTargetValue* _tmp230_ = NULL;
				ValaTargetValue* _tmp231_;
				_tmp214_ = expr;
				_tmp215_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp214_);
				_tmp216_ = _tmp215_;
				_tmp217_ = _vala_code_node_ref0 (VALA_FIELD (_tmp216_));
				f = _tmp217_;
				_tmp219_ = expr;
				_tmp220_ = vala_member_access_get_inner (_tmp219_);
				_tmp221_ = _tmp220_;
				if (_tmp221_ != NULL) {
					ValaMemberAccess* _tmp222_;
					ValaExpression* _tmp223_;
					ValaExpression* _tmp224_;
					ValaTargetValue* _tmp225_;
					ValaTargetValue* _tmp226_;
					_tmp222_ = expr;
					_tmp223_ = vala_member_access_get_inner (_tmp222_);
					_tmp224_ = _tmp223_;
					_tmp225_ = vala_expression_get_target_value (_tmp224_);
					_tmp226_ = _tmp225_;
					_tmp218_ = _tmp226_;
				} else {
					_tmp218_ = NULL;
				}
				_tmp227_ = expr;
				_tmp228_ = f;
				_tmp229_ = _tmp218_;
				_tmp230_ = vala_code_generator_load_field ((ValaCodeGenerator*) self, _tmp228_, _tmp229_);
				_tmp231_ = _tmp230_;
				vala_expression_set_target_value ((ValaExpression*) _tmp227_, _tmp231_);
				_vala_target_value_unref0 (_tmp231_);
				_vala_code_node_unref0 (f);
			} else {
				ValaMemberAccess* _tmp232_;
				ValaSymbol* _tmp233_;
				ValaSymbol* _tmp234_;
				_tmp232_ = expr;
				_tmp233_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp232_);
				_tmp234_ = _tmp233_;
				if (VALA_IS_ENUM_VALUE (_tmp234_)) {
					ValaMemberAccess* _tmp235_;
					ValaSymbol* _tmp236_;
					ValaSymbol* _tmp237_;
					ValaEnumValue* _tmp238_;
					ValaEnumValue* ev;
					ValaEnumValue* _tmp239_;
					ValaSymbol* _tmp240_;
					ValaSymbol* _tmp241_;
					ValaCCodeFile* _tmp242_;
					ValaMemberAccess* _tmp243_;
					ValaEnumValue* _tmp244_;
					gchar* _tmp245_ = NULL;
					gchar* _tmp246_;
					ValaCCodeConstant* _tmp247_;
					ValaCCodeConstant* _tmp248_;
					_tmp235_ = expr;
					_tmp236_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp235_);
					_tmp237_ = _tmp236_;
					_tmp238_ = _vala_code_node_ref0 (VALA_ENUM_VALUE (_tmp237_));
					ev = _tmp238_;
					_tmp239_ = ev;
					_tmp240_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp239_);
					_tmp241_ = _tmp240_;
					_tmp242_ = ((ValaDovaBaseModule*) self)->cfile;
					vala_dova_base_module_generate_enum_declaration ((ValaDovaBaseModule*) self, VALA_ENUM (_tmp241_), _tmp242_);
					_tmp243_ = expr;
					_tmp244_ = ev;
					_tmp245_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp244_);
					_tmp246_ = _tmp245_;
					_tmp247_ = vala_ccode_constant_new (_tmp246_);
					_tmp248_ = _tmp247_;
					vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp243_, (ValaCCodeExpression*) _tmp248_);
					_vala_ccode_node_unref0 (_tmp248_);
					_g_free0 (_tmp246_);
					_vala_code_node_unref0 (ev);
				} else {
					ValaMemberAccess* _tmp249_;
					ValaSymbol* _tmp250_;
					ValaSymbol* _tmp251_;
					_tmp249_ = expr;
					_tmp250_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp249_);
					_tmp251_ = _tmp250_;
					if (VALA_IS_CONSTANT (_tmp251_)) {
						ValaMemberAccess* _tmp252_;
						ValaSymbol* _tmp253_;
						ValaSymbol* _tmp254_;
						ValaConstant* _tmp255_;
						ValaConstant* c;
						ValaConstant* _tmp256_;
						ValaCCodeFile* _tmp257_;
						ValaMemberAccess* _tmp258_;
						ValaConstant* _tmp259_;
						gchar* _tmp260_ = NULL;
						gchar* _tmp261_;
						ValaCCodeIdentifier* _tmp262_;
						ValaCCodeIdentifier* _tmp263_;
						_tmp252_ = expr;
						_tmp253_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp252_);
						_tmp254_ = _tmp253_;
						_tmp255_ = _vala_code_node_ref0 (VALA_CONSTANT (_tmp254_));
						c = _tmp255_;
						_tmp256_ = c;
						_tmp257_ = ((ValaDovaBaseModule*) self)->cfile;
						vala_dova_base_module_generate_constant_declaration ((ValaDovaBaseModule*) self, _tmp256_, _tmp257_);
						_tmp258_ = expr;
						_tmp259_ = c;
						_tmp260_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp259_);
						_tmp261_ = _tmp260_;
						_tmp262_ = vala_ccode_identifier_new (_tmp261_);
						_tmp263_ = _tmp262_;
						vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp258_, (ValaCCodeExpression*) _tmp263_);
						_vala_ccode_node_unref0 (_tmp263_);
						_g_free0 (_tmp261_);
						_vala_code_node_unref0 (c);
					} else {
						ValaMemberAccess* _tmp264_;
						ValaSymbol* _tmp265_;
						ValaSymbol* _tmp266_;
						_tmp264_ = expr;
						_tmp265_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp264_);
						_tmp266_ = _tmp265_;
						if (VALA_IS_PROPERTY (_tmp266_)) {
							ValaMemberAccess* _tmp267_;
							ValaSymbol* _tmp268_;
							ValaSymbol* _tmp269_;
							ValaProperty* _tmp270_;
							ValaProperty* prop;
							ValaProperty* _tmp271_;
							ValaMemberAccess* _tmp287_;
							ValaExpression* _tmp288_;
							ValaExpression* _tmp289_;
							ValaProperty* _tmp373_;
							ValaProperty* _tmp374_;
							ValaProperty* base_property;
							ValaProperty* _tmp375_;
							ValaProperty* _tmp376_;
							ValaProperty* _tmp377_;
							ValaProperty* _tmp389_;
							ValaPropertyAccessor* _tmp390_;
							ValaPropertyAccessor* _tmp391_;
							gchar* _tmp392_ = NULL;
							gchar* getter_cname;
							const gchar* _tmp393_;
							ValaCCodeIdentifier* _tmp394_;
							ValaCCodeIdentifier* _tmp395_;
							ValaCCodeFunctionCall* _tmp396_;
							ValaCCodeFunctionCall* _tmp397_;
							ValaCCodeFunctionCall* ccall;
							ValaProperty* _tmp398_;
							ValaMemberBinding _tmp399_;
							ValaMemberBinding _tmp400_;
							ValaMemberAccess* _tmp403_;
							ValaCCodeFunctionCall* _tmp404_;
							_tmp267_ = expr;
							_tmp268_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp267_);
							_tmp269_ = _tmp268_;
							_tmp270_ = _vala_code_node_ref0 (VALA_PROPERTY (_tmp269_));
							prop = _tmp270_;
							_tmp271_ = prop;
							if (!VALA_IS_DYNAMIC_PROPERTY (_tmp271_)) {
								ValaProperty* _tmp272_;
								ValaPropertyAccessor* _tmp273_;
								ValaPropertyAccessor* _tmp274_;
								ValaCCodeFile* _tmp275_;
								gboolean _tmp276_ = FALSE;
								ValaProperty* _tmp277_;
								gboolean _tmp278_;
								gboolean _tmp279_;
								gboolean _tmp283_;
								_tmp272_ = prop;
								_tmp273_ = vala_property_get_get_accessor (_tmp272_);
								_tmp274_ = _tmp273_;
								_tmp275_ = ((ValaDovaBaseModule*) self)->cfile;
								vala_dova_base_module_generate_property_accessor_declaration ((ValaDovaBaseModule*) self, _tmp274_, _tmp275_);
								_tmp277_ = prop;
								_tmp278_ = vala_symbol_get_external ((ValaSymbol*) _tmp277_);
								_tmp279_ = _tmp278_;
								if (!_tmp279_) {
									ValaProperty* _tmp280_;
									gboolean _tmp281_;
									gboolean _tmp282_;
									_tmp280_ = prop;
									_tmp281_ = vala_symbol_get_external_package ((ValaSymbol*) _tmp280_);
									_tmp282_ = _tmp281_;
									_tmp276_ = _tmp282_;
								} else {
									_tmp276_ = FALSE;
								}
								_tmp283_ = _tmp276_;
								if (_tmp283_) {
									ValaProperty* _tmp284_;
									gboolean _tmp285_ = FALSE;
									_tmp284_ = prop;
									_tmp285_ = vala_dova_base_module_add_generated_external_symbol ((ValaDovaBaseModule*) self, (ValaSymbol*) _tmp284_);
									if (_tmp285_) {
										ValaProperty* _tmp286_;
										_tmp286_ = prop;
										vala_code_visitor_visit_property ((ValaCodeVisitor*) self, _tmp286_);
									}
								}
							}
							_tmp287_ = expr;
							_tmp288_ = vala_member_access_get_inner (_tmp287_);
							_tmp289_ = _tmp288_;
							if (VALA_IS_BASE_ACCESS (_tmp289_)) {
								ValaProperty* _tmp290_;
								ValaProperty* _tmp291_;
								ValaProperty* _tmp292_;
								_tmp290_ = prop;
								_tmp291_ = vala_property_get_base_property (_tmp290_);
								_tmp292_ = _tmp291_;
								if (_tmp292_ != NULL) {
									ValaProperty* _tmp293_;
									ValaProperty* _tmp294_;
									ValaProperty* _tmp295_;
									ValaSymbol* _tmp296_;
									ValaSymbol* _tmp297_;
									ValaClass* _tmp298_;
									ValaClass* base_class;
									ValaClass* _tmp299_;
									gchar* _tmp300_ = NULL;
									gchar* _tmp301_;
									gchar* _tmp302_ = NULL;
									gchar* _tmp303_;
									ValaCCodeIdentifier* _tmp304_;
									ValaCCodeIdentifier* _tmp305_;
									ValaCCodeFunctionCall* _tmp306_;
									ValaCCodeFunctionCall* _tmp307_;
									ValaCCodeFunctionCall* vcast;
									ValaCCodeFunctionCall* _tmp308_;
									ValaClass* _tmp309_;
									ValaClass* _tmp310_;
									gchar* _tmp311_ = NULL;
									gchar* _tmp312_;
									gchar* _tmp313_ = NULL;
									gchar* _tmp314_;
									ValaCCodeIdentifier* _tmp315_;
									ValaCCodeIdentifier* _tmp316_;
									ValaCCodeFunctionCall* _tmp317_;
									ValaProperty* _tmp318_;
									const gchar* _tmp319_;
									const gchar* _tmp320_;
									gchar* _tmp321_ = NULL;
									gchar* _tmp322_;
									ValaCCodeMemberAccess* _tmp323_;
									ValaCCodeMemberAccess* _tmp324_;
									ValaCCodeFunctionCall* _tmp325_;
									ValaCCodeFunctionCall* _tmp326_;
									ValaCCodeFunctionCall* ccall;
									ValaCCodeFunctionCall* _tmp327_;
									ValaMemberAccess* _tmp328_;
									ValaExpression* _tmp329_;
									ValaExpression* _tmp330_;
									ValaCCodeExpression* _tmp331_ = NULL;
									ValaCCodeExpression* _tmp332_;
									ValaMemberAccess* _tmp333_;
									ValaCCodeFunctionCall* _tmp334_;
									_tmp293_ = prop;
									_tmp294_ = vala_property_get_base_property (_tmp293_);
									_tmp295_ = _tmp294_;
									_tmp296_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp295_);
									_tmp297_ = _tmp296_;
									_tmp298_ = _vala_code_node_ref0 (VALA_CLASS (_tmp297_));
									base_class = _tmp298_;
									_tmp299_ = base_class;
									_tmp300_ = vala_dova_base_module_get_ccode_upper_case_name ((ValaDovaBaseModule*) self, (ValaSymbol*) _tmp299_, NULL);
									_tmp301_ = _tmp300_;
									_tmp302_ = g_strdup_printf ("%s_CLASS", _tmp301_);
									_tmp303_ = _tmp302_;
									_tmp304_ = vala_ccode_identifier_new (_tmp303_);
									_tmp305_ = _tmp304_;
									_tmp306_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp305_);
									_tmp307_ = _tmp306_;
									_vala_ccode_node_unref0 (_tmp305_);
									_g_free0 (_tmp303_);
									_g_free0 (_tmp301_);
									vcast = _tmp307_;
									_tmp308_ = vcast;
									_tmp309_ = vala_dova_base_module_get_current_class ((ValaDovaBaseModule*) self);
									_tmp310_ = _tmp309_;
									_tmp311_ = vala_dova_base_module_get_ccode_lower_case_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp310_, NULL);
									_tmp312_ = _tmp311_;
									_tmp313_ = g_strdup_printf ("%s_parent_class", _tmp312_);
									_tmp314_ = _tmp313_;
									_tmp315_ = vala_ccode_identifier_new (_tmp314_);
									_tmp316_ = _tmp315_;
									vala_ccode_function_call_add_argument (_tmp308_, (ValaCCodeExpression*) _tmp316_);
									_vala_ccode_node_unref0 (_tmp316_);
									_g_free0 (_tmp314_);
									_g_free0 (_tmp312_);
									_tmp317_ = vcast;
									_tmp318_ = prop;
									_tmp319_ = vala_symbol_get_name ((ValaSymbol*) _tmp318_);
									_tmp320_ = _tmp319_;
									_tmp321_ = g_strdup_printf ("get_%s", _tmp320_);
									_tmp322_ = _tmp321_;
									_tmp323_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) _tmp317_, _tmp322_);
									_tmp324_ = _tmp323_;
									_tmp325_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp324_);
									_tmp326_ = _tmp325_;
									_vala_ccode_node_unref0 (_tmp324_);
									_g_free0 (_tmp322_);
									ccall = _tmp326_;
									_tmp327_ = ccall;
									_tmp328_ = expr;
									_tmp329_ = vala_member_access_get_inner (_tmp328_);
									_tmp330_ = _tmp329_;
									_tmp331_ = vala_dova_base_module_get_cvalue ((ValaDovaBaseModule*) self, _tmp330_);
									_tmp332_ = _tmp331_;
									vala_ccode_function_call_add_argument (_tmp327_, _tmp332_);
									_vala_ccode_node_unref0 (_tmp332_);
									_tmp333_ = expr;
									_tmp334_ = ccall;
									vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp333_, (ValaCCodeExpression*) _tmp334_);
									_vala_ccode_node_unref0 (ccall);
									_vala_ccode_node_unref0 (vcast);
									_vala_code_node_unref0 (base_class);
									_vala_code_node_unref0 (prop);
									_vala_code_node_unref0 (base_type);
									_vala_ccode_node_unref0 (pub_inst);
									return;
								} else {
									ValaProperty* _tmp335_;
									ValaProperty* _tmp336_;
									ValaProperty* _tmp337_;
									_tmp335_ = prop;
									_tmp336_ = vala_property_get_base_interface_property (_tmp335_);
									_tmp337_ = _tmp336_;
									if (_tmp337_ != NULL) {
										ValaProperty* _tmp338_;
										ValaProperty* _tmp339_;
										ValaProperty* _tmp340_;
										ValaSymbol* _tmp341_;
										ValaSymbol* _tmp342_;
										ValaInterface* _tmp343_;
										ValaInterface* base_iface;
										ValaClass* _tmp344_;
										ValaClass* _tmp345_;
										gchar* _tmp346_ = NULL;
										gchar* _tmp347_;
										ValaInterface* _tmp348_;
										gchar* _tmp349_ = NULL;
										gchar* _tmp350_;
										gchar* _tmp351_ = NULL;
										gchar* _tmp352_;
										gchar* parent_iface_var;
										const gchar* _tmp353_;
										ValaCCodeIdentifier* _tmp354_;
										ValaCCodeIdentifier* _tmp355_;
										ValaProperty* _tmp356_;
										const gchar* _tmp357_;
										const gchar* _tmp358_;
										gchar* _tmp359_ = NULL;
										gchar* _tmp360_;
										ValaCCodeMemberAccess* _tmp361_;
										ValaCCodeMemberAccess* _tmp362_;
										ValaCCodeFunctionCall* _tmp363_;
										ValaCCodeFunctionCall* _tmp364_;
										ValaCCodeFunctionCall* ccall;
										ValaCCodeFunctionCall* _tmp365_;
										ValaMemberAccess* _tmp366_;
										ValaExpression* _tmp367_;
										ValaExpression* _tmp368_;
										ValaCCodeExpression* _tmp369_ = NULL;
										ValaCCodeExpression* _tmp370_;
										ValaMemberAccess* _tmp371_;
										ValaCCodeFunctionCall* _tmp372_;
										_tmp338_ = prop;
										_tmp339_ = vala_property_get_base_interface_property (_tmp338_);
										_tmp340_ = _tmp339_;
										_tmp341_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp340_);
										_tmp342_ = _tmp341_;
										_tmp343_ = _vala_code_node_ref0 (VALA_INTERFACE (_tmp342_));
										base_iface = _tmp343_;
										_tmp344_ = vala_dova_base_module_get_current_class ((ValaDovaBaseModule*) self);
										_tmp345_ = _tmp344_;
										_tmp346_ = vala_dova_base_module_get_ccode_lower_case_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp345_, NULL);
										_tmp347_ = _tmp346_;
										_tmp348_ = base_iface;
										_tmp349_ = vala_dova_base_module_get_ccode_lower_case_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp348_, NULL);
										_tmp350_ = _tmp349_;
										_tmp351_ = g_strdup_printf ("%s_%s_parent_iface", _tmp347_, _tmp350_);
										_tmp352_ = _tmp351_;
										_g_free0 (_tmp350_);
										_g_free0 (_tmp347_);
										parent_iface_var = _tmp352_;
										_tmp353_ = parent_iface_var;
										_tmp354_ = vala_ccode_identifier_new (_tmp353_);
										_tmp355_ = _tmp354_;
										_tmp356_ = prop;
										_tmp357_ = vala_symbol_get_name ((ValaSymbol*) _tmp356_);
										_tmp358_ = _tmp357_;
										_tmp359_ = g_strdup_printf ("get_%s", _tmp358_);
										_tmp360_ = _tmp359_;
										_tmp361_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) _tmp355_, _tmp360_);
										_tmp362_ = _tmp361_;
										_tmp363_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp362_);
										_tmp364_ = _tmp363_;
										_vala_ccode_node_unref0 (_tmp362_);
										_g_free0 (_tmp360_);
										_vala_ccode_node_unref0 (_tmp355_);
										ccall = _tmp364_;
										_tmp365_ = ccall;
										_tmp366_ = expr;
										_tmp367_ = vala_member_access_get_inner (_tmp366_);
										_tmp368_ = _tmp367_;
										_tmp369_ = vala_dova_base_module_get_cvalue ((ValaDovaBaseModule*) self, _tmp368_);
										_tmp370_ = _tmp369_;
										vala_ccode_function_call_add_argument (_tmp365_, _tmp370_);
										_vala_ccode_node_unref0 (_tmp370_);
										_tmp371_ = expr;
										_tmp372_ = ccall;
										vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp371_, (ValaCCodeExpression*) _tmp372_);
										_vala_ccode_node_unref0 (ccall);
										_g_free0 (parent_iface_var);
										_vala_code_node_unref0 (base_iface);
										_vala_code_node_unref0 (prop);
										_vala_code_node_unref0 (base_type);
										_vala_ccode_node_unref0 (pub_inst);
										return;
									}
								}
							}
							_tmp373_ = prop;
							_tmp374_ = _vala_code_node_ref0 (_tmp373_);
							base_property = _tmp374_;
							_tmp375_ = prop;
							_tmp376_ = vala_property_get_base_property (_tmp375_);
							_tmp377_ = _tmp376_;
							if (_tmp377_ != NULL) {
								ValaProperty* _tmp378_;
								ValaProperty* _tmp379_;
								ValaProperty* _tmp380_;
								ValaProperty* _tmp381_;
								_tmp378_ = prop;
								_tmp379_ = vala_property_get_base_property (_tmp378_);
								_tmp380_ = _tmp379_;
								_tmp381_ = _vala_code_node_ref0 (_tmp380_);
								_vala_code_node_unref0 (base_property);
								base_property = _tmp381_;
							} else {
								ValaProperty* _tmp382_;
								ValaProperty* _tmp383_;
								ValaProperty* _tmp384_;
								_tmp382_ = prop;
								_tmp383_ = vala_property_get_base_interface_property (_tmp382_);
								_tmp384_ = _tmp383_;
								if (_tmp384_ != NULL) {
									ValaProperty* _tmp385_;
									ValaProperty* _tmp386_;
									ValaProperty* _tmp387_;
									ValaProperty* _tmp388_;
									_tmp385_ = prop;
									_tmp386_ = vala_property_get_base_interface_property (_tmp385_);
									_tmp387_ = _tmp386_;
									_tmp388_ = _vala_code_node_ref0 (_tmp387_);
									_vala_code_node_unref0 (base_property);
									base_property = _tmp388_;
								}
							}
							_tmp389_ = base_property;
							_tmp390_ = vala_property_get_get_accessor (_tmp389_);
							_tmp391_ = _tmp390_;
							_tmp392_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp391_);
							getter_cname = _tmp392_;
							_tmp393_ = getter_cname;
							_tmp394_ = vala_ccode_identifier_new (_tmp393_);
							_tmp395_ = _tmp394_;
							_tmp396_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp395_);
							_tmp397_ = _tmp396_;
							_vala_ccode_node_unref0 (_tmp395_);
							ccall = _tmp397_;
							_tmp398_ = prop;
							_tmp399_ = vala_property_get_binding (_tmp398_);
							_tmp400_ = _tmp399_;
							if (_tmp400_ == VALA_MEMBER_BINDING_INSTANCE) {
								ValaCCodeFunctionCall* _tmp401_;
								ValaCCodeExpression* _tmp402_;
								_tmp401_ = ccall;
								_tmp402_ = pub_inst;
								vala_ccode_function_call_add_argument (_tmp401_, _tmp402_);
							}
							_tmp403_ = expr;
							_tmp404_ = ccall;
							vala_dova_base_module_set_cvalue ((ValaDovaBaseModule*) self, (ValaExpression*) _tmp403_, (ValaCCodeExpression*) _tmp404_);
							_vala_ccode_node_unref0 (ccall);
							_g_free0 (getter_cname);
							_vala_code_node_unref0 (base_property);
							_vala_code_node_unref0 (prop);
						} else {
							ValaMemberAccess* _tmp405_;
							ValaSymbol* _tmp406_;
							ValaSymbol* _tmp407_;
							_tmp405_ = expr;
							_tmp406_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp405_);
							_tmp407_ = _tmp406_;
							if (VALA_IS_LOCAL_VARIABLE (_tmp407_)) {
								ValaMemberAccess* _tmp408_;
								ValaSymbol* _tmp409_;
								ValaSymbol* _tmp410_;
								ValaLocalVariable* _tmp411_;
								ValaLocalVariable* local;
								ValaMemberAccess* _tmp412_;
								ValaLocalVariable* _tmp413_;
								ValaTargetValue* _tmp414_ = NULL;
								ValaTargetValue* _tmp415_;
								_tmp408_ = expr;
								_tmp409_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp408_);
								_tmp410_ = _tmp409_;
								_tmp411_ = _vala_code_node_ref0 (VALA_LOCAL_VARIABLE (_tmp410_));
								local = _tmp411_;
								_tmp412_ = expr;
								_tmp413_ = local;
								_tmp414_ = vala_code_generator_load_local ((ValaCodeGenerator*) self, _tmp413_);
								_tmp415_ = _tmp414_;
								vala_expression_set_target_value ((ValaExpression*) _tmp412_, _tmp415_);
								_vala_target_value_unref0 (_tmp415_);
								_vala_code_node_unref0 (local);
							} else {
								ValaMemberAccess* _tmp416_;
								ValaSymbol* _tmp417_;
								ValaSymbol* _tmp418_;
								_tmp416_ = expr;
								_tmp417_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp416_);
								_tmp418_ = _tmp417_;
								if (VALA_IS_PARAMETER (_tmp418_)) {
									ValaMemberAccess* _tmp419_;
									ValaSymbol* _tmp420_;
									ValaSymbol* _tmp421_;
									ValaParameter* _tmp422_;
									ValaParameter* p;
									ValaMemberAccess* _tmp423_;
									ValaParameter* _tmp424_;
									ValaTargetValue* _tmp425_ = NULL;
									ValaTargetValue* _tmp426_;
									_tmp419_ = expr;
									_tmp420_ = vala_expression_get_symbol_reference ((ValaExpression*) _tmp419_);
									_tmp421_ = _tmp420_;
									_tmp422_ = _vala_code_node_ref0 (VALA_PARAMETER (_tmp421_));
									p = _tmp422_;
									_tmp423_ = expr;
									_tmp424_ = p;
									_tmp425_ = vala_code_generator_load_parameter ((ValaCodeGenerator*) self, _tmp424_);
									_tmp426_ = _tmp425_;
									vala_expression_set_target_value ((ValaExpression*) _tmp423_, _tmp426_);
									_vala_target_value_unref0 (_tmp426_);
									_vala_code_node_unref0 (p);
								}
							}
						}
					}
				}
			}
		}
	}
	_vala_code_node_unref0 (base_type);
	_vala_ccode_node_unref0 (pub_inst);
}


ValaTargetValue* vala_dova_member_access_module_get_local_cvalue (ValaDovaMemberAccessModule* self, ValaLocalVariable* local) {
	ValaTargetValue* result = NULL;
	ValaLocalVariable* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDovaValue* _tmp3_;
	ValaDovaValue* _result_;
	ValaLocalVariable* _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp6_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (local != NULL, NULL);
	_tmp0_ = local;
	_tmp1_ = vala_variable_get_variable_type ((ValaVariable*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_dova_value_new (_tmp2_, NULL);
	_result_ = _tmp3_;
	_tmp4_ = local;
	_tmp5_ = vala_local_variable_get_is_result (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_) {
		ValaDovaValue* _tmp7_;
		ValaCCodeIdentifier* _tmp8_;
		_tmp7_ = _result_;
		_tmp8_ = vala_ccode_identifier_new ("result");
		_vala_ccode_node_unref0 (_tmp7_->cvalue);
		_tmp7_->cvalue = (ValaCCodeExpression*) _tmp8_;
	} else {
		ValaLocalVariable* _tmp9_;
		gboolean _tmp10_;
		gboolean _tmp11_;
		_tmp9_ = local;
		_tmp10_ = vala_local_variable_get_captured (_tmp9_);
		_tmp11_ = _tmp10_;
		if (_tmp11_) {
			ValaLocalVariable* _tmp12_;
			ValaSymbol* _tmp13_;
			ValaSymbol* _tmp14_;
			ValaBlock* _tmp15_;
			ValaBlock* block;
			ValaDovaValue* _tmp16_;
			ValaBlock* _tmp17_;
			gint _tmp18_ = 0;
			gchar* _tmp19_ = NULL;
			gchar* _tmp20_;
			ValaCCodeExpression* _tmp21_ = NULL;
			ValaCCodeExpression* _tmp22_;
			ValaLocalVariable* _tmp23_;
			const gchar* _tmp24_;
			const gchar* _tmp25_;
			gchar* _tmp26_ = NULL;
			gchar* _tmp27_;
			ValaCCodeMemberAccess* _tmp28_;
			_tmp12_ = local;
			_tmp13_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp12_);
			_tmp14_ = _tmp13_;
			_tmp15_ = _vala_code_node_ref0 (VALA_BLOCK (_tmp14_));
			block = _tmp15_;
			_tmp16_ = _result_;
			_tmp17_ = block;
			_tmp18_ = vala_dova_base_module_get_block_id ((ValaDovaBaseModule*) self, _tmp17_);
			_tmp19_ = g_strdup_printf ("_data%d_", _tmp18_);
			_tmp20_ = _tmp19_;
			_tmp21_ = vala_dova_base_module_get_variable_cexpression ((ValaDovaBaseModule*) self, _tmp20_);
			_tmp22_ = _tmp21_;
			_tmp23_ = local;
			_tmp24_ = vala_symbol_get_name ((ValaSymbol*) _tmp23_);
			_tmp25_ = _tmp24_;
			_tmp26_ = vala_dova_base_module_get_variable_cname ((ValaDovaBaseModule*) self, _tmp25_);
			_tmp27_ = _tmp26_;
			_tmp28_ = vala_ccode_member_access_new_pointer (_tmp22_, _tmp27_);
			_vala_ccode_node_unref0 (_tmp16_->cvalue);
			_tmp16_->cvalue = (ValaCCodeExpression*) _tmp28_;
			_g_free0 (_tmp27_);
			_vala_ccode_node_unref0 (_tmp22_);
			_g_free0 (_tmp20_);
			_vala_code_node_unref0 (block);
		} else {
			ValaDovaValue* _tmp29_;
			ValaLocalVariable* _tmp30_;
			const gchar* _tmp31_;
			const gchar* _tmp32_;
			ValaCCodeExpression* _tmp33_ = NULL;
			_tmp29_ = _result_;
			_tmp30_ = local;
			_tmp31_ = vala_symbol_get_name ((ValaSymbol*) _tmp30_);
			_tmp32_ = _tmp31_;
			_tmp33_ = vala_dova_base_module_get_variable_cexpression ((ValaDovaBaseModule*) self, _tmp32_);
			_vala_ccode_node_unref0 (_tmp29_->cvalue);
			_tmp29_->cvalue = _tmp33_;
		}
	}
	result = (ValaTargetValue*) _result_;
	return result;
}


ValaTargetValue* vala_dova_member_access_module_get_parameter_cvalue (ValaDovaMemberAccessModule* self, ValaParameter* p) {
	ValaTargetValue* result = NULL;
	ValaParameter* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDovaValue* _tmp3_;
	ValaDovaValue* _result_;
	ValaParameter* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (p != NULL, NULL);
	_tmp0_ = p;
	_tmp1_ = vala_variable_get_variable_type ((ValaVariable*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_dova_value_new (_tmp2_, NULL);
	_result_ = _tmp3_;
	_tmp4_ = p;
	_tmp5_ = vala_symbol_get_name ((ValaSymbol*) _tmp4_);
	_tmp6_ = _tmp5_;
	if (g_strcmp0 (_tmp6_, "this") == 0) {
		gboolean _tmp7_ = FALSE;
		ValaMethod* _tmp8_;
		ValaMethod* _tmp9_;
		gboolean _tmp14_;
		_tmp8_ = vala_dova_base_module_get_current_method ((ValaDovaBaseModule*) self);
		_tmp9_ = _tmp8_;
		if (_tmp9_ != NULL) {
			ValaMethod* _tmp10_;
			ValaMethod* _tmp11_;
			gboolean _tmp12_;
			gboolean _tmp13_;
			_tmp10_ = vala_dova_base_module_get_current_method ((ValaDovaBaseModule*) self);
			_tmp11_ = _tmp10_;
			_tmp12_ = vala_method_get_coroutine (_tmp11_);
			_tmp13_ = _tmp12_;
			_tmp7_ = _tmp13_;
		} else {
			_tmp7_ = FALSE;
		}
		_tmp14_ = _tmp7_;
		if (_tmp14_) {
			ValaDovaValue* _tmp15_;
			ValaCCodeIdentifier* _tmp16_;
			ValaCCodeIdentifier* _tmp17_;
			ValaCCodeMemberAccess* _tmp18_;
			_tmp15_ = _result_;
			_tmp16_ = vala_ccode_identifier_new ("data");
			_tmp17_ = _tmp16_;
			_tmp18_ = vala_ccode_member_access_new_pointer ((ValaCCodeExpression*) _tmp17_, "this");
			_vala_ccode_node_unref0 (_tmp15_->cvalue);
			_tmp15_->cvalue = (ValaCCodeExpression*) _tmp18_;
			_vala_ccode_node_unref0 (_tmp17_);
		} else {
			ValaTypeSymbol* _tmp19_;
			ValaTypeSymbol* _tmp20_;
			ValaStruct* _tmp21_;
			ValaStruct* st;
			gboolean _tmp22_ = FALSE;
			gboolean _tmp23_ = FALSE;
			gboolean _tmp24_ = FALSE;
			gboolean _tmp25_ = FALSE;
			ValaStruct* _tmp26_;
			gboolean _tmp29_;
			gboolean _tmp32_;
			gboolean _tmp35_;
			gboolean _tmp42_;
			_tmp19_ = vala_dova_base_module_get_current_type_symbol ((ValaDovaBaseModule*) self);
			_tmp20_ = _tmp19_;
			_tmp21_ = _vala_code_node_ref0 (VALA_IS_STRUCT (_tmp20_) ? ((ValaStruct*) _tmp20_) : NULL);
			st = _tmp21_;
			_tmp26_ = st;
			if (_tmp26_ != NULL) {
				ValaStruct* _tmp27_;
				gboolean _tmp28_ = FALSE;
				_tmp27_ = st;
				_tmp28_ = vala_struct_is_boolean_type (_tmp27_);
				_tmp25_ = !_tmp28_;
			} else {
				_tmp25_ = FALSE;
			}
			_tmp29_ = _tmp25_;
			if (_tmp29_) {
				ValaStruct* _tmp30_;
				gboolean _tmp31_ = FALSE;
				_tmp30_ = st;
				_tmp31_ = vala_struct_is_integer_type (_tmp30_);
				_tmp24_ = !_tmp31_;
			} else {
				_tmp24_ = FALSE;
			}
			_tmp32_ = _tmp24_;
			if (_tmp32_) {
				ValaStruct* _tmp33_;
				gboolean _tmp34_ = FALSE;
				_tmp33_ = st;
				_tmp34_ = vala_struct_is_floating_type (_tmp33_);
				_tmp23_ = !_tmp34_;
			} else {
				_tmp23_ = FALSE;
			}
			_tmp35_ = _tmp23_;
			if (_tmp35_) {
				gboolean _tmp36_ = FALSE;
				ValaStruct* _tmp37_;
				gboolean _tmp38_ = FALSE;
				gboolean _tmp41_;
				_tmp37_ = st;
				_tmp38_ = vala_struct_is_simple_type (_tmp37_);
				if (!_tmp38_) {
					_tmp36_ = TRUE;
				} else {
					ValaMethod* _tmp39_;
					ValaMethod* _tmp40_;
					_tmp39_ = vala_dova_base_module_get_current_method ((ValaDovaBaseModule*) self);
					_tmp40_ = _tmp39_;
					_tmp36_ = VALA_IS_CREATION_METHOD (_tmp40_);
				}
				_tmp41_ = _tmp36_;
				_tmp22_ = _tmp41_;
			} else {
				_tmp22_ = FALSE;
			}
			_tmp42_ = _tmp22_;
			if (_tmp42_) {
				ValaDovaValue* _tmp43_;
				ValaCCodeIdentifier* _tmp44_;
				_tmp43_ = _result_;
				_tmp44_ = vala_ccode_identifier_new ("(*this)");
				_vala_ccode_node_unref0 (_tmp43_->cvalue);
				_tmp43_->cvalue = (ValaCCodeExpression*) _tmp44_;
			} else {
				ValaDovaValue* _tmp45_;
				ValaCCodeIdentifier* _tmp46_;
				_tmp45_ = _result_;
				_tmp46_ = vala_ccode_identifier_new ("this");
				_vala_ccode_node_unref0 (_tmp45_->cvalue);
				_tmp45_->cvalue = (ValaCCodeExpression*) _tmp46_;
			}
			_vala_code_node_unref0 (st);
		}
	} else {
		ValaParameter* _tmp47_;
		gboolean _tmp48_;
		gboolean _tmp49_;
		_tmp47_ = p;
		_tmp48_ = vala_parameter_get_captured (_tmp47_);
		_tmp49_ = _tmp48_;
		if (_tmp49_) {
			ValaParameter* _tmp50_;
			ValaSymbol* _tmp51_;
			ValaSymbol* _tmp52_;
			ValaBlock* _tmp53_;
			ValaBlock* block;
			ValaBlock* _tmp54_;
			ValaDovaValue* _tmp61_;
			ValaBlock* _tmp62_;
			gint _tmp63_ = 0;
			gchar* _tmp64_ = NULL;
			gchar* _tmp65_;
			ValaCCodeExpression* _tmp66_ = NULL;
			ValaCCodeExpression* _tmp67_;
			ValaParameter* _tmp68_;
			const gchar* _tmp69_;
			const gchar* _tmp70_;
			gchar* _tmp71_ = NULL;
			gchar* _tmp72_;
			ValaCCodeMemberAccess* _tmp73_;
			_tmp50_ = p;
			_tmp51_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp50_);
			_tmp52_ = _tmp51_;
			_tmp53_ = _vala_code_node_ref0 (VALA_IS_BLOCK (_tmp52_) ? ((ValaBlock*) _tmp52_) : NULL);
			block = _tmp53_;
			_tmp54_ = block;
			if (_tmp54_ == NULL) {
				ValaParameter* _tmp55_;
				ValaSymbol* _tmp56_;
				ValaSymbol* _tmp57_;
				ValaBlock* _tmp58_;
				ValaBlock* _tmp59_;
				ValaBlock* _tmp60_;
				_tmp55_ = p;
				_tmp56_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp55_);
				_tmp57_ = _tmp56_;
				_tmp58_ = vala_subroutine_get_body ((ValaSubroutine*) VALA_METHOD (_tmp57_));
				_tmp59_ = _tmp58_;
				_tmp60_ = _vala_code_node_ref0 (_tmp59_);
				_vala_code_node_unref0 (block);
				block = _tmp60_;
			}
			_tmp61_ = _result_;
			_tmp62_ = block;
			_tmp63_ = vala_dova_base_module_get_block_id ((ValaDovaBaseModule*) self, _tmp62_);
			_tmp64_ = g_strdup_printf ("_data%d_", _tmp63_);
			_tmp65_ = _tmp64_;
			_tmp66_ = vala_dova_base_module_get_variable_cexpression ((ValaDovaBaseModule*) self, _tmp65_);
			_tmp67_ = _tmp66_;
			_tmp68_ = p;
			_tmp69_ = vala_symbol_get_name ((ValaSymbol*) _tmp68_);
			_tmp70_ = _tmp69_;
			_tmp71_ = vala_dova_base_module_get_variable_cname ((ValaDovaBaseModule*) self, _tmp70_);
			_tmp72_ = _tmp71_;
			_tmp73_ = vala_ccode_member_access_new_pointer (_tmp67_, _tmp72_);
			_vala_ccode_node_unref0 (_tmp61_->cvalue);
			_tmp61_->cvalue = (ValaCCodeExpression*) _tmp73_;
			_g_free0 (_tmp72_);
			_vala_ccode_node_unref0 (_tmp67_);
			_g_free0 (_tmp65_);
			_vala_code_node_unref0 (block);
		} else {
			gboolean _tmp74_ = FALSE;
			ValaMethod* _tmp75_;
			ValaMethod* _tmp76_;
			gboolean _tmp81_;
			_tmp75_ = vala_dova_base_module_get_current_method ((ValaDovaBaseModule*) self);
			_tmp76_ = _tmp75_;
			if (_tmp76_ != NULL) {
				ValaMethod* _tmp77_;
				ValaMethod* _tmp78_;
				gboolean _tmp79_;
				gboolean _tmp80_;
				_tmp77_ = vala_dova_base_module_get_current_method ((ValaDovaBaseModule*) self);
				_tmp78_ = _tmp77_;
				_tmp79_ = vala_method_get_coroutine (_tmp78_);
				_tmp80_ = _tmp79_;
				_tmp74_ = _tmp80_;
			} else {
				_tmp74_ = FALSE;
			}
			_tmp81_ = _tmp74_;
			if (_tmp81_) {
				ValaDovaValue* _tmp82_;
				ValaParameter* _tmp83_;
				const gchar* _tmp84_;
				const gchar* _tmp85_;
				ValaCCodeExpression* _tmp86_ = NULL;
				_tmp82_ = _result_;
				_tmp83_ = p;
				_tmp84_ = vala_symbol_get_name ((ValaSymbol*) _tmp83_);
				_tmp85_ = _tmp84_;
				_tmp86_ = vala_dova_base_module_get_variable_cexpression ((ValaDovaBaseModule*) self, _tmp85_);
				_vala_ccode_node_unref0 (_tmp82_->cvalue);
				_tmp82_->cvalue = _tmp86_;
			} else {
				ValaParameter* _tmp87_;
				ValaDataType* _tmp88_;
				ValaDataType* _tmp89_;
				ValaTypeSymbol* _tmp90_;
				ValaTypeSymbol* _tmp91_;
				ValaStruct* _tmp92_;
				ValaStruct* type_as_struct;
				gboolean _tmp93_ = FALSE;
				ValaParameter* _tmp94_;
				ValaParameterDirection _tmp95_;
				ValaParameterDirection _tmp96_;
				gboolean _tmp109_;
				_tmp87_ = p;
				_tmp88_ = vala_variable_get_variable_type ((ValaVariable*) _tmp87_);
				_tmp89_ = _tmp88_;
				_tmp90_ = vala_data_type_get_data_type (_tmp89_);
				_tmp91_ = _tmp90_;
				_tmp92_ = _vala_code_node_ref0 (VALA_IS_STRUCT (_tmp91_) ? ((ValaStruct*) _tmp91_) : NULL);
				type_as_struct = _tmp92_;
				_tmp94_ = p;
				_tmp95_ = vala_parameter_get_direction (_tmp94_);
				_tmp96_ = _tmp95_;
				if (_tmp96_ != VALA_PARAMETER_DIRECTION_IN) {
					_tmp93_ = TRUE;
				} else {
					gboolean _tmp97_ = FALSE;
					gboolean _tmp98_ = FALSE;
					ValaStruct* _tmp99_;
					gboolean _tmp102_;
					gboolean _tmp108_;
					_tmp99_ = type_as_struct;
					if (_tmp99_ != NULL) {
						ValaStruct* _tmp100_;
						gboolean _tmp101_ = FALSE;
						_tmp100_ = type_as_struct;
						_tmp101_ = vala_struct_is_simple_type (_tmp100_);
						_tmp98_ = !_tmp101_;
					} else {
						_tmp98_ = FALSE;
					}
					_tmp102_ = _tmp98_;
					if (_tmp102_) {
						ValaParameter* _tmp103_;
						ValaDataType* _tmp104_;
						ValaDataType* _tmp105_;
						gboolean _tmp106_;
						gboolean _tmp107_;
						_tmp103_ = p;
						_tmp104_ = vala_variable_get_variable_type ((ValaVariable*) _tmp103_);
						_tmp105_ = _tmp104_;
						_tmp106_ = vala_data_type_get_nullable (_tmp105_);
						_tmp107_ = _tmp106_;
						_tmp97_ = !_tmp107_;
					} else {
						_tmp97_ = FALSE;
					}
					_tmp108_ = _tmp97_;
					_tmp93_ = _tmp108_;
				}
				_tmp109_ = _tmp93_;
				if (_tmp109_) {
					ValaParameter* _tmp110_;
					ValaDataType* _tmp111_;
					ValaDataType* _tmp112_;
					_tmp110_ = p;
					_tmp111_ = vala_variable_get_variable_type ((ValaVariable*) _tmp110_);
					_tmp112_ = _tmp111_;
					if (VALA_IS_GENERIC_TYPE (_tmp112_)) {
						ValaDovaValue* _tmp113_;
						ValaParameter* _tmp114_;
						const gchar* _tmp115_;
						const gchar* _tmp116_;
						ValaCCodeExpression* _tmp117_ = NULL;
						_tmp113_ = _result_;
						_tmp114_ = p;
						_tmp115_ = vala_symbol_get_name ((ValaSymbol*) _tmp114_);
						_tmp116_ = _tmp115_;
						_tmp117_ = vala_dova_base_module_get_variable_cexpression ((ValaDovaBaseModule*) self, _tmp116_);
						_vala_ccode_node_unref0 (_tmp113_->cvalue);
						_tmp113_->cvalue = _tmp117_;
					} else {
						ValaDovaValue* _tmp118_;
						ValaParameter* _tmp119_;
						const gchar* _tmp120_;
						const gchar* _tmp121_;
						gchar* _tmp122_ = NULL;
						gchar* _tmp123_;
						gchar* _tmp124_ = NULL;
						gchar* _tmp125_;
						ValaCCodeIdentifier* _tmp126_;
						_tmp118_ = _result_;
						_tmp119_ = p;
						_tmp120_ = vala_symbol_get_name ((ValaSymbol*) _tmp119_);
						_tmp121_ = _tmp120_;
						_tmp122_ = vala_dova_base_module_get_variable_cname ((ValaDovaBaseModule*) self, _tmp121_);
						_tmp123_ = _tmp122_;
						_tmp124_ = g_strdup_printf ("(*%s)", _tmp123_);
						_tmp125_ = _tmp124_;
						_tmp126_ = vala_ccode_identifier_new (_tmp125_);
						_vala_ccode_node_unref0 (_tmp118_->cvalue);
						_tmp118_->cvalue = (ValaCCodeExpression*) _tmp126_;
						_g_free0 (_tmp125_);
						_g_free0 (_tmp123_);
					}
				} else {
					gboolean _tmp127_ = FALSE;
					gboolean _tmp128_ = FALSE;
					gboolean _tmp129_ = FALSE;
					ValaPropertyAccessor* _tmp130_;
					ValaPropertyAccessor* _tmp131_;
					gboolean _tmp136_;
					gboolean _tmp142_;
					gboolean _tmp150_;
					_tmp130_ = vala_dova_base_module_get_current_property_accessor ((ValaDovaBaseModule*) self);
					_tmp131_ = _tmp130_;
					if (_tmp131_ != NULL) {
						ValaPropertyAccessor* _tmp132_;
						ValaPropertyAccessor* _tmp133_;
						gboolean _tmp134_;
						gboolean _tmp135_;
						_tmp132_ = vala_dova_base_module_get_current_property_accessor ((ValaDovaBaseModule*) self);
						_tmp133_ = _tmp132_;
						_tmp134_ = vala_property_accessor_get_writable (_tmp133_);
						_tmp135_ = _tmp134_;
						_tmp129_ = _tmp135_;
					} else {
						_tmp129_ = FALSE;
					}
					_tmp136_ = _tmp129_;
					if (_tmp136_) {
						ValaPropertyAccessor* _tmp137_;
						ValaPropertyAccessor* _tmp138_;
						ValaParameter* _tmp139_;
						ValaParameter* _tmp140_;
						ValaParameter* _tmp141_;
						_tmp137_ = vala_dova_base_module_get_current_property_accessor ((ValaDovaBaseModule*) self);
						_tmp138_ = _tmp137_;
						_tmp139_ = vala_property_accessor_get_value_parameter (_tmp138_);
						_tmp140_ = _tmp139_;
						_tmp141_ = p;
						_tmp128_ = _tmp140_ == _tmp141_;
					} else {
						_tmp128_ = FALSE;
					}
					_tmp142_ = _tmp128_;
					if (_tmp142_) {
						ValaPropertyAccessor* _tmp143_;
						ValaPropertyAccessor* _tmp144_;
						ValaProperty* _tmp145_;
						ValaProperty* _tmp146_;
						ValaDataType* _tmp147_;
						ValaDataType* _tmp148_;
						gboolean _tmp149_ = FALSE;
						_tmp143_ = vala_dova_base_module_get_current_property_accessor ((ValaDovaBaseModule*) self);
						_tmp144_ = _tmp143_;
						_tmp145_ = vala_property_accessor_get_prop (_tmp144_);
						_tmp146_ = _tmp145_;
						_tmp147_ = vala_property_get_property_type (_tmp146_);
						_tmp148_ = _tmp147_;
						_tmp149_ = vala_data_type_is_real_struct_type (_tmp148_);
						_tmp127_ = _tmp149_;
					} else {
						_tmp127_ = FALSE;
					}
					_tmp150_ = _tmp127_;
					if (_tmp150_) {
						ValaDovaValue* _tmp151_;
						ValaCCodeIdentifier* _tmp152_;
						_tmp151_ = _result_;
						_tmp152_ = vala_ccode_identifier_new ("(*value)");
						_vala_ccode_node_unref0 (_tmp151_->cvalue);
						_tmp151_->cvalue = (ValaCCodeExpression*) _tmp152_;
					} else {
						ValaDovaValue* _tmp153_;
						ValaParameter* _tmp154_;
						const gchar* _tmp155_;
						const gchar* _tmp156_;
						ValaCCodeExpression* _tmp157_ = NULL;
						_tmp153_ = _result_;
						_tmp154_ = p;
						_tmp155_ = vala_symbol_get_name ((ValaSymbol*) _tmp154_);
						_tmp156_ = _tmp155_;
						_tmp157_ = vala_dova_base_module_get_variable_cexpression ((ValaDovaBaseModule*) self, _tmp156_);
						_vala_ccode_node_unref0 (_tmp153_->cvalue);
						_tmp153_->cvalue = _tmp157_;
					}
				}
				_vala_code_node_unref0 (type_as_struct);
			}
		}
	}
	result = (ValaTargetValue*) _result_;
	return result;
}


ValaTargetValue* vala_dova_member_access_module_get_field_cvalue (ValaDovaMemberAccessModule* self, ValaField* f, ValaTargetValue* instance) {
	ValaTargetValue* result = NULL;
	ValaField* _tmp0_;
	ValaDataType* _tmp1_;
	ValaDataType* _tmp2_;
	ValaDovaValue* _tmp3_;
	ValaDovaValue* _result_;
	ValaField* _tmp4_;
	ValaMemberBinding _tmp5_;
	ValaMemberBinding _tmp6_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (f != NULL, NULL);
	_tmp0_ = f;
	_tmp1_ = vala_variable_get_variable_type ((ValaVariable*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_dova_value_new (_tmp2_, NULL);
	_result_ = _tmp3_;
	_tmp4_ = f;
	_tmp5_ = vala_field_get_binding (_tmp4_);
	_tmp6_ = _tmp5_;
	if (_tmp6_ == VALA_MEMBER_BINDING_INSTANCE) {
		ValaCCodeExpression* pub_inst;
		ValaTargetValue* _tmp7_;
		ValaField* _tmp10_;
		ValaSymbol* _tmp11_;
		ValaSymbol* _tmp12_;
		ValaDataType* _tmp13_ = NULL;
		ValaDataType* instance_target_type;
		ValaDataType* _tmp14_;
		ValaTypeSymbol* _tmp15_;
		ValaTypeSymbol* _tmp16_;
		ValaClass* _tmp17_;
		ValaClass* cl;
		gboolean dova_priv;
		gboolean _tmp18_ = FALSE;
		ValaField* _tmp19_;
		ValaSymbolAccessibility _tmp20_;
		ValaSymbolAccessibility _tmp21_;
		gboolean _tmp25_;
		ValaCCodeExpression* inst = NULL;
		gboolean _tmp26_;
		gboolean _tmp42_ = FALSE;
		ValaDataType* _tmp43_;
		ValaTypeSymbol* _tmp44_;
		ValaTypeSymbol* _tmp45_;
		gboolean _tmp46_ = FALSE;
		gboolean _tmp53_;
		pub_inst = NULL;
		_tmp7_ = instance;
		if (_tmp7_ != NULL) {
			ValaTargetValue* _tmp8_;
			ValaCCodeExpression* _tmp9_ = NULL;
			_tmp8_ = instance;
			_tmp9_ = vala_dova_base_module_get_cvalue_ ((ValaDovaBaseModule*) self, _tmp8_);
			_vala_ccode_node_unref0 (pub_inst);
			pub_inst = _tmp9_;
		}
		_tmp10_ = f;
		_tmp11_ = vala_symbol_get_parent_symbol ((ValaSymbol*) _tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = vala_dova_base_module_get_data_type_for_symbol (VALA_TYPESYMBOL (_tmp12_));
		instance_target_type = _tmp13_;
		_tmp14_ = instance_target_type;
		_tmp15_ = vala_data_type_get_data_type (_tmp14_);
		_tmp16_ = _tmp15_;
		_tmp17_ = _vala_code_node_ref0 (VALA_IS_CLASS (_tmp16_) ? ((ValaClass*) _tmp16_) : NULL);
		cl = _tmp17_;
		dova_priv = FALSE;
		_tmp19_ = f;
		_tmp20_ = vala_symbol_get_access ((ValaSymbol*) _tmp19_);
		_tmp21_ = _tmp20_;
		if (_tmp21_ == VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
			_tmp18_ = TRUE;
		} else {
			ValaField* _tmp22_;
			ValaSymbolAccessibility _tmp23_;
			ValaSymbolAccessibility _tmp24_;
			_tmp22_ = f;
			_tmp23_ = vala_symbol_get_access ((ValaSymbol*) _tmp22_);
			_tmp24_ = _tmp23_;
			_tmp18_ = _tmp24_ == VALA_SYMBOL_ACCESSIBILITY_INTERNAL;
		}
		_tmp25_ = _tmp18_;
		if (_tmp25_) {
			dova_priv = TRUE;
		}
		_tmp26_ = dova_priv;
		if (_tmp26_) {
			ValaClass* _tmp27_;
			gchar* _tmp28_ = NULL;
			gchar* _tmp29_;
			gchar* _tmp30_ = NULL;
			gchar* _tmp31_;
			ValaCCodeIdentifier* _tmp32_;
			ValaCCodeIdentifier* _tmp33_;
			ValaCCodeFunctionCall* _tmp34_;
			ValaCCodeFunctionCall* _tmp35_;
			ValaCCodeFunctionCall* priv_call;
			ValaCCodeFunctionCall* _tmp36_;
			ValaCCodeExpression* _tmp37_;
			ValaCCodeFunctionCall* _tmp38_;
			ValaCCodeExpression* _tmp39_;
			_tmp27_ = cl;
			_tmp28_ = vala_dova_base_module_get_ccode_upper_case_name ((ValaDovaBaseModule*) self, (ValaSymbol*) _tmp27_, NULL);
			_tmp29_ = _tmp28_;
			_tmp30_ = g_strdup_printf ("%s_GET_PRIVATE", _tmp29_);
			_tmp31_ = _tmp30_;
			_tmp32_ = vala_ccode_identifier_new (_tmp31_);
			_tmp33_ = _tmp32_;
			_tmp34_ = vala_ccode_function_call_new ((ValaCCodeExpression*) _tmp33_);
			_tmp35_ = _tmp34_;
			_vala_ccode_node_unref0 (_tmp33_);
			_g_free0 (_tmp31_);
			_g_free0 (_tmp29_);
			priv_call = _tmp35_;
			_tmp36_ = priv_call;
			_tmp37_ = pub_inst;
			vala_ccode_function_call_add_argument (_tmp36_, _tmp37_);
			_tmp38_ = priv_call;
			_tmp39_ = _vala_ccode_node_ref0 ((ValaCCodeExpression*) _tmp38_);
			_vala_ccode_node_unref0 (inst);
			inst = _tmp39_;
			_vala_ccode_node_unref0 (priv_call);
		} else {
			ValaCCodeExpression* _tmp40_;
			ValaCCodeExpression* _tmp41_;
			_tmp40_ = pub_inst;
			_tmp41_ = _vala_ccode_node_ref0 (_tmp40_);
			_vala_ccode_node_unref0 (inst);
			inst = _tmp41_;
		}
		_tmp43_ = instance_target_type;
		_tmp44_ = vala_data_type_get_data_type (_tmp43_);
		_tmp45_ = _tmp44_;
		_tmp46_ = vala_typesymbol_is_reference_type (_tmp45_);
		if (_tmp46_) {
			_tmp42_ = TRUE;
		} else {
			gboolean _tmp47_ = FALSE;
			ValaTargetValue* _tmp48_;
			gboolean _tmp52_;
			_tmp48_ = instance;
			if (_tmp48_ != NULL) {
				ValaTargetValue* _tmp49_;
				ValaDataType* _tmp50_;
				ValaDataType* _tmp51_;
				_tmp49_ = instance;
				_tmp50_ = vala_target_value_get_value_type (_tmp49_);
				_tmp51_ = _tmp50_;
				_tmp47_ = VALA_IS_POINTER_TYPE (_tmp51_);
			} else {
				_tmp47_ = FALSE;
			}
			_tmp52_ = _tmp47_;
			_tmp42_ = _tmp52_;
		}
		_tmp53_ = _tmp42_;
		if (_tmp53_) {
			ValaDovaValue* _tmp54_;
			ValaCCodeExpression* _tmp55_;
			ValaField* _tmp56_;
			gchar* _tmp57_ = NULL;
			gchar* _tmp58_;
			ValaCCodeMemberAccess* _tmp59_;
			_tmp54_ = _result_;
			_tmp55_ = inst;
			_tmp56_ = f;
			_tmp57_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp56_);
			_tmp58_ = _tmp57_;
			_tmp59_ = vala_ccode_member_access_new_pointer (_tmp55_, _tmp58_);
			_vala_ccode_node_unref0 (_tmp54_->cvalue);
			_tmp54_->cvalue = (ValaCCodeExpression*) _tmp59_;
			_g_free0 (_tmp58_);
		} else {
			ValaDovaValue* _tmp60_;
			ValaCCodeExpression* _tmp61_;
			ValaField* _tmp62_;
			gchar* _tmp63_ = NULL;
			gchar* _tmp64_;
			ValaCCodeMemberAccess* _tmp65_;
			_tmp60_ = _result_;
			_tmp61_ = inst;
			_tmp62_ = f;
			_tmp63_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp62_);
			_tmp64_ = _tmp63_;
			_tmp65_ = vala_ccode_member_access_new (_tmp61_, _tmp64_, FALSE);
			_vala_ccode_node_unref0 (_tmp60_->cvalue);
			_tmp60_->cvalue = (ValaCCodeExpression*) _tmp65_;
			_g_free0 (_tmp64_);
		}
		_vala_ccode_node_unref0 (inst);
		_vala_code_node_unref0 (cl);
		_vala_code_node_unref0 (instance_target_type);
		_vala_ccode_node_unref0 (pub_inst);
	} else {
		ValaField* _tmp66_;
		ValaCCodeFile* _tmp67_;
		ValaDovaValue* _tmp68_;
		ValaField* _tmp69_;
		gchar* _tmp70_ = NULL;
		gchar* _tmp71_;
		ValaCCodeIdentifier* _tmp72_;
		_tmp66_ = f;
		_tmp67_ = ((ValaDovaBaseModule*) self)->cfile;
		vala_dova_base_module_generate_field_declaration ((ValaDovaBaseModule*) self, _tmp66_, _tmp67_);
		_tmp68_ = _result_;
		_tmp69_ = f;
		_tmp70_ = vala_dova_base_module_get_ccode_name ((ValaDovaBaseModule*) self, (ValaCodeNode*) _tmp69_);
		_tmp71_ = _tmp70_;
		_tmp72_ = vala_ccode_identifier_new (_tmp71_);
		_vala_ccode_node_unref0 (_tmp68_->cvalue);
		_tmp68_->cvalue = (ValaCCodeExpression*) _tmp72_;
		_g_free0 (_tmp71_);
	}
	result = (ValaTargetValue*) _result_;
	return result;
}


static gpointer _vala_target_value_ref0 (gpointer self) {
	return self ? vala_target_value_ref (self) : NULL;
}


static ValaTargetValue* vala_dova_member_access_module_load_variable (ValaDovaMemberAccessModule* self, ValaVariable* variable, ValaTargetValue* value) {
	ValaTargetValue* result = NULL;
	ValaTargetValue* _tmp0_;
	ValaTargetValue* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (variable != NULL, NULL);
	g_return_val_if_fail (value != NULL, NULL);
	_tmp0_ = value;
	_tmp1_ = _vala_target_value_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


static ValaTargetValue* vala_dova_member_access_module_real_load_local (ValaCodeGenerator* base, ValaLocalVariable* local) {
	ValaDovaMemberAccessModule * self;
	ValaTargetValue* result = NULL;
	ValaLocalVariable* _tmp0_;
	ValaLocalVariable* _tmp1_;
	ValaTargetValue* _tmp2_ = NULL;
	ValaTargetValue* _tmp3_;
	ValaTargetValue* _tmp4_ = NULL;
	ValaTargetValue* _tmp5_;
	self = (ValaDovaMemberAccessModule*) base;
	g_return_val_if_fail (local != NULL, NULL);
	_tmp0_ = local;
	_tmp1_ = local;
	_tmp2_ = vala_dova_member_access_module_get_local_cvalue (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_dova_member_access_module_load_variable (self, (ValaVariable*) _tmp0_, _tmp3_);
	_tmp5_ = _tmp4_;
	_vala_target_value_unref0 (_tmp3_);
	result = _tmp5_;
	return result;
}


static ValaTargetValue* vala_dova_member_access_module_real_load_parameter (ValaCodeGenerator* base, ValaParameter* param) {
	ValaDovaMemberAccessModule * self;
	ValaTargetValue* result = NULL;
	ValaParameter* _tmp0_;
	ValaParameter* _tmp1_;
	ValaTargetValue* _tmp2_ = NULL;
	ValaTargetValue* _tmp3_;
	ValaTargetValue* _tmp4_ = NULL;
	ValaTargetValue* _tmp5_;
	self = (ValaDovaMemberAccessModule*) base;
	g_return_val_if_fail (param != NULL, NULL);
	_tmp0_ = param;
	_tmp1_ = param;
	_tmp2_ = vala_dova_member_access_module_get_parameter_cvalue (self, _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = vala_dova_member_access_module_load_variable (self, (ValaVariable*) _tmp0_, _tmp3_);
	_tmp5_ = _tmp4_;
	_vala_target_value_unref0 (_tmp3_);
	result = _tmp5_;
	return result;
}


static ValaTargetValue* vala_dova_member_access_module_real_load_field (ValaCodeGenerator* base, ValaField* field, ValaTargetValue* instance) {
	ValaDovaMemberAccessModule * self;
	ValaTargetValue* result = NULL;
	ValaField* _tmp0_;
	ValaField* _tmp1_;
	ValaTargetValue* _tmp2_;
	ValaTargetValue* _tmp3_ = NULL;
	ValaTargetValue* _tmp4_;
	ValaTargetValue* _tmp5_ = NULL;
	ValaTargetValue* _tmp6_;
	self = (ValaDovaMemberAccessModule*) base;
	g_return_val_if_fail (field != NULL, NULL);
	_tmp0_ = field;
	_tmp1_ = field;
	_tmp2_ = instance;
	_tmp3_ = vala_dova_member_access_module_get_field_cvalue (self, _tmp1_, _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = vala_dova_member_access_module_load_variable (self, (ValaVariable*) _tmp0_, _tmp4_);
	_tmp6_ = _tmp5_;
	_vala_target_value_unref0 (_tmp4_);
	result = _tmp6_;
	return result;
}


ValaDovaMemberAccessModule* vala_dova_member_access_module_construct (GType object_type) {
	ValaDovaMemberAccessModule* self = NULL;
	self = (ValaDovaMemberAccessModule*) vala_dova_control_flow_module_construct (object_type);
	return self;
}


static void vala_dova_member_access_module_class_init (ValaDovaMemberAccessModuleClass * klass) {
	vala_dova_member_access_module_parent_class = g_type_class_peek_parent (klass);
	VALA_CODE_VISITOR_CLASS (klass)->visit_member_access = vala_dova_member_access_module_real_visit_member_access;
	VALA_CODE_GENERATOR_CLASS (klass)->load_local = vala_dova_member_access_module_real_load_local;
	VALA_CODE_GENERATOR_CLASS (klass)->load_parameter = vala_dova_member_access_module_real_load_parameter;
	VALA_CODE_GENERATOR_CLASS (klass)->load_field = vala_dova_member_access_module_real_load_field;
}


static void vala_dova_member_access_module_instance_init (ValaDovaMemberAccessModule * self) {
}


GType vala_dova_member_access_module_get_type (void) {
	static volatile gsize vala_dova_member_access_module_type_id__volatile = 0;
	if (g_once_init_enter (&vala_dova_member_access_module_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ValaDovaMemberAccessModuleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_dova_member_access_module_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValaDovaMemberAccessModule), 0, (GInstanceInitFunc) vala_dova_member_access_module_instance_init, NULL };
		GType vala_dova_member_access_module_type_id;
		vala_dova_member_access_module_type_id = g_type_register_static (VALA_TYPE_DOVA_CONTROL_FLOW_MODULE, "ValaDovaMemberAccessModule", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&vala_dova_member_access_module_type_id__volatile, vala_dova_member_access_module_type_id);
	}
	return vala_dova_member_access_module_type_id__volatile;
}



